### ISSUE TITLE
mouseup / mousedown events are not firing

### ISSUE THREAD

**Issue by stefanholzapfel** [Polymer/lit-html#1013]
Hi!

This does log output to the console on click:

`<div @click="${ event => { console.log("TEST") }  }"></div>`

This not:

`<div @mousedown="${ event => { console.log("TEST") }  }"></div>`
OR
`<div @mouseup="${ event => { console.log("TEST") }  }"></div>`

What am I getting wrong?

Thank you!

**Comment by Westbrook** [comment]
The code above works pretty well for me.

Do you happen to have a repro of your issue? There may be something related to this code that is tripping up your app...

**Comment by jsilvermist** [comment]
May be related to touch? When using mousedown/mouseup also use touchstart/touchend.

**Comment by pbastowski** [comment]
Your code works fine for me, but I had to add some content to the example divs, otherwise there is nothing to click on.

Some of the questions below may be basic, but...

Are you transpiling code using a build system? Does it support arrow functions properly? 

Do you get any errors in the console or nothing at all?

Are you, perhaps, using lit-html directly in the browser without a build step?

Does your browser support arrow functions?

**Comment by stefanholzapfel** [comment]
Hi!

Thanks for the respsones.

Devtools open / closed doesn't make a difference.
I'm transpiling from typescript via webpack.
Yes lambda functions are supported, otherwise the click event wouldn't work as well.

I have just tried to create the same div on the root level and there it works. So I guess the problem has something to do with the swiper (https://swiperjs.com/) in which the div is embedded. Obviously swiper affects some of it's childrens events somehow.

Thanks for the hint @jsilvermist
