### ISSUE TITLE
document/decide on how selects with computed options should behave

### ISSUE THREAD

**Issue by 43081j** [Polymer/lit-html#1052]
Take this example:
https://stackblitz.com/edit/lit-element-demo-trexqs

If you have a `select` with its `value` property bound to something, things work fine:

```ts
render(html`<select .value=${foo}>
  <option value="a">A</option>
  <option value="b">B</option>
</select>`, node);
```

However, if the options are computed (i.e. sub-templates):

```ts
const options = someArray.map((i) => html`<option>${i}</option>`);

render(html`<select .value=${foo}>
  ${options}
</select>`, node);
```

The options are added to DOM **after** the `value` property of the select is set, meaning the select ultimately defaults to the first option every time.

We should probably document this somewhere or decide what to do with it. Its expected behaviour, i think, but could lead to a fair amount of confusion seeing as this is a fairly common use case.

cc @justinfagnani

**Comment by justinfagnani** [comment]
It seems like React and Preact special-case certain properties like `value` and `checked` due to this issue. They "re-sync" them after the initial render. That kind of sucks, because it'll add weight to the library, but we could do the same.

I wonder if there's a more general solution for properties/attributes that depend on child content? Maybe this is something the `live()` directive could do?

cc @developit who I asked about this.

**Comment by hyperpress** [comment]
Would a select resync be added to directives so case optional?

**Comment by justinfagnani** [comment]
@hyperpress we could do that, but I think it puts a lot of burden on developers (and our docs).

**Comment by hyperpress** [comment]
Thinking about that more, I see your points. It's definitely a case that
comes up. Looking at live() for reference.

**Comment by daKmoR** [comment]
are we talking about https://open-wc.org/developing/lit-helpers.html#live-binding or is there an official live directive somewhere now? 🤗

**Comment by justinfagnani** [comment]
Talking about that in general, which is still a potential first-class directive to add here to address #877.

**Comment by frank-dspeed** [comment]
@justinfagnani as the template result is bundled inside a template tag we can do some easy thing we could re insert the complet rendered template into a new template in a whole befor rendering it that adds less overhead as long as the source template is not inserted into the dom which should not be the case at all.

other trick that workarounds this behavior is to append the template result via getTemplate to the DOM and render from that the dom it self will handle that then.

**Comment by frank-dspeed** [comment]
a other workaround is a good logic like

```js
const options = (selected) => ['a', 'b', 'c'].map((opt) => html`<option value=${opt} ${selected === opt ? 'selected' : ''}>${opt}</option>`)

render(
  html`<select .value=${defaultValue}>
    ${options(defaultValue)}
  </select>`,document.querySelector('.foo'))
```
in this case options is aware what is the default option and then all will work right as expected

**Comment by frank-dspeed** [comment]
the main failure in your syntax is that it is missing the sleected attr of the option which gets set by the dom sure but thats only a hack in valid markup the option node it self should get selected by the markup creator like active property for menu items in navbars

**Comment by blikblum** [comment]
I just hit this issue. Added an example [here](https://webcomponents.dev/edit/ivtTbu8884P1D7wKTlTJ): it shows the behavior of predefined and dynamic options setting select value or setting option selected. Also tests what happens when rerendering or toggling value 

AFAICS `live` directive would help when re rendering but would not help to set the correct value at first render.

**Comment by justinfagnani** [comment]
We've added the `live()` directive for this case.
