### ISSUE TITLE
direct access to NodePart, AttributePart, BooleanAttributePart, EventPart

### ISSUE THREAD

**Issue by surinder83singh** [Polymer/lit-html#1081]
we are rendering 3k+ records, happy with lit-html rendering/update speed.

but records are editable, during edit mode there is input element which overlap on record html row.
when user finish his editing and click "save" button, we want to hide input elements immediately,  but now we dont want to build/render complete rows again to see newly entered values into html rows, if we do so, build/render takes some time and  first we see new values in input, then input becomes invisible, then we see old values in html rows then after few seconds we see new values, which seems crazy. 

if we directly update html nodes for new values,  then "cancel changes" dont show old values.
did not tried "live" directive, but i think it will effect speed of rendering 

so i think there should be a way to directly access required "part" of template so that we can update html nodes using `part.setValue("new value"); part.commit(); `

**Comment by kevinpschaaf** [comment]
The `directive` API provides access to the `part` to allow for async/out-of-render updating.  Please check out https://lit-html.polymer-project.org/guide/creating-directives and consider defining a directive that works for your use case.  Closing for now, since without seeing the exact code pattern you're trying to optimize it's hard to suggest exactly how to go about it, but please open a new issue if the directive API does not suffice.
