### ISSUE TITLE
lit-html's template polyfill broken on IE11

### ISSUE THREAD

**Issue by wkeese** [Polymer/lit-html#1089]
# Description
Lit-html's template polyfill (in polyfills/template_polyfill.js) doesn't work on IE11.  It throws a `NotSupportedExcepton` because `element.content` is undefined.   `@webcomponents/template`, on the other hand, works fine.

A related issue is that template_polyfill.js is in ES6 syntax, which makes it impossible to load on IE without a babel transpilation step.  It seems a bit silly to write it in ES6 when it will only be used on an ES5 browser.  

# Steps to Reproduce

I  loaded `lit-html` through the `es6!` plugin, i.e. doing the transpilation on the browser.   Not sure if that makes a difference.

I had to fix a few bugs in the `es6!` plugin before it would work at all.  My code is at https://github.com/wkeese/requirejs-babel/tree/path-fixes, and the test file is demo/index.html.

## Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ X] IE 11

**Comment by graynorton** [comment]
Background: this polyfill was added for a very specific use case, targeting a specific browser.

We need to look at this issue and see what makes sense. Possibilities include:

* Fixing the issue
* Documenting the limitation
* Splitting this polyfill out of lit-html altogether, as it arguably doesn't really belong here (this would obviously be a breaking change from a SemVer point of view)

**Comment by wkeese** [comment]
Which browser were you targeting?   The only place it's needed is on IE11 (see https://caniuse.com/#search=template) so it would be weird if you were targeting a different browser.

**Comment by justinfagnani** [comment]
It is a bit weird, but this template polyfill is mainly for the YouTube Cobalt browser: https://cobalt.foo/ and only in applications that don't otherwise use `<template>` directly.

If you need a spec-compliant template polyfill for other uses, please do use `@webcomponents/template`.

As the polyfill states here: https://github.com/Polymer/lit-html/blob/master/src/polyfills/template_polyfill.ts#L18 this is specifically written to only implement the minimim set of features for lit-html to work. We have a [test runner](https://github.com/Polymer/lit-html/blob/master/test/no-template.html) that runs all the lit-html tests with this polyfill forced on. If none of those fail, we're fine. The code is written as ES6 because this version is expected to be compiled with the app using it.

You report is confusing, because the polyfill does roughly implement `.content`. Are you seeing an error only while using lit-html, or do you have other code that directly uses template?

**Comment by wkeese** [comment]
That is not the browser I expected :-).

Anyway, I figured out what the issue was.   It's not enough to just include and transpile the template polyfill, you need to call its export, like this:

```
import { initTemplatePolyfill } from "lit-html/polyfills/template_polyfill";
initTemplatePolyfill();
```

Also, before that, you need to import some other polyfill code to get `Object.assign()` etc.:

```
import "@babel/polyfill";
```

After that it works!
