### ISSUE TITLE
Cannot set multiple event listeners for the same event on the same node

### ISSUE THREAD

**Issue by e111077** [Polymer/lit-html#1139]
# Description

lit-html does not let you set two event listeners on the same event on the same node.
# Steps to Reproduce

1. add two different event listeners to the same node with the same event

e.g.

```ts
html`<button @click=${onClick} @click=${foundationHandleClick}></button>`
```

2. render the template

## Live Reproduction Link

https://stackblitz.com/edit/typescript-hqicsa

## Expected Results

both event listeners would be called (preferably in markup order) on click

## Actual Results

Compilation fails in stackblitz and error is thrown in ES6 and does not render.

ES6 error:

```
Uncaught (in promise) TypeError: Cannot read property 'split' of null
```

at this line:

https://github.com/Polymer/lit-html/blob/master/src/lib/template.ts#L108

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [x] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by justinfagnani** [comment]
I'm not sure we can reasonably fix this, since duplicate attributes are discarded by the HTML parser. That's also the source of the exception. We can probably get a warning added to eslint-plugin-lit though. Another idea might be to write a directive that can accept multiple listeners.

Until something like that, can you just do that manually though?

```ts
html`<button @click=${_onClick}></button>`

function _onClick(e) {
  onClick(e);
  foundationHandleClick(e);
}
```

**Comment by jridgewell** [comment]
Maybe support passing an array of listeners?

**Comment by e111077** [comment]
been using that workaround but it's kinda gross to have `onClick` and `protected onClick_`. if it's impossible to do multiple of the same, an array would work, but `@eventOptions` would be weird to implement, no?

**Comment by sorvell** [comment]
Composing the events yourself is pretty straightforward. It seems like the only thing that is tricky with this approach is emulating `stopImmediatePropagation` since there is no flag to check on that. This would only be an issue when this is code you do not control, however.

Given that there's a simple solution here, adding code to lit-html to address this seems a little hard to justify. If we support support Arrays, we have to add code to diff the contents to add/remove the listeners.

**Comment by sorvell** [comment]
Closing based on previous comment. If there is more feedback on this issue we may consider it again in the future.

**Comment by sedwards2009** [comment]
I'm in the situation right now where I want a listener for a focus event and also another one on focus but with `capture: true`. It doesn't seem possible to do this at all via pure lit-html though. An array would be nice.

**Comment by justinfagnani** [comment]
@sedwards2009 Since capturing event listeners are a superset of non-capturing, I would recommend adding a capturing listener in the template and have that delegate to the two listeners.

Otherwise, I'm still a bit wary of adding the complexity of multiple event listeners to core. I'd need to see how much code it took.

**Comment by sedwards2009** [comment]
@justinfagnani  DOM's `Element.addEventListener()` lets you trigger a listener during either the "capture" or "bubbling" phase of event propagation. A capturing event listener won't see events during the bubble phase though, which makes then not a superset. So you can't delegate from one listener function.
