### ISSUE TITLE
Give directives access to RenderOptions

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#1143]
Directives may need to access the host element that templates are rendered into. We already have this information in the RenderOptions object.

This will enable directives to do things like add events listeners to the host, await `updateComplete`, etc. These things now require that a directive accept the host via parameter, or get the host via the DOM with getRootNode(). RenderOptions, or other parameters to the directive, may be a more ergonomic and documentable API.

**Comment by zandaqo** [comment]
This would be great. Any ETA on this? Is there anything blocking this at the moment?

I'm particularly interested in getting access to the host element. I'm using LitElement and I can get to the host (custom element) in directives that deal with EventParts (through EventPart#eventContext), but I have to send it via parameter elsewhere since getRootNode returns unattached DocumentElement till it's, well, attached, hence, it's unreliable.

**Comment by web-padawan** [comment]
Hi, is this something planned to be implemented in `lit-next` branch?

**Comment by web-padawan** [comment]
Hi, is there any update regarding directives for 2.x? Do you have plans to implement this in `lit-next` branch?

**Comment by sorvell** [comment]
The design of Directives is being worked on in the `lit-next` branch and it's still a work in progress. I recommend following work in that branch and posting issues with a `[lit-next]` prefix/label to discuss potential features and use cases. Thanks!

**Comment by sorvell** [comment]
We're considering adding this in the next major version. See #1441.
