### ISSUE TITLE
Problem with template containing contenteditable element

### ISSUE THREAD

**Issue by hokiedsp** [Polymer/lit-html#1156]
# Description

I encountered what appears to be a bug while trying to implement a template containing an editable DIV. What I ultimately want to accomplish is to switch between a label and its format string, and make the format string editable when focused then auto-update the label when the DIV is blurred. 

But it is failing on me likely due to browsers' handling of lit-html's  placeholders in the innerHTML of the DIV during editing. The placeholders disappear when content is "aggressively" edited. Below is the simplest example that I could come up to illustrate the issue.

# Steps to Reproduce

1. Write this code

```javascript

import { html, render } from "https://unpkg.com/lit-html/lit-html.js";

var div = document.body;
var data = {
  edit: false,
  label: "Test",
  formatter: "Edit Me",
  toggle: () => {
    data.edit = !data.edit;
    render(template(data), div);
  }
};

var template = (data) => html`<div
  contenteditable
  @focus=${data.toggle}
  @blur=${data.toggle}
>
  ${data.edit ? data.formatter : data.label}
</div>`;

render(template(data), div);
```

2. See this output...

## Live Reproduction Link
https://codepen.io/hokiedsp/details/WNQZxPE

## Expected Results
Text to toggle between 2 preset texts ("Test" and "Edit Me") after focus/blur event on the DIV, wiping out any changes made by user

## Actual Results
- Works properly as long as new characters are added with some text is remaining
- If all the text ('Edit Me') is selected and edit over it, it eventually quits refreshing the text.
- In Chrome, appending a character wipes out and the DIV goes empty (works in Firefox)

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11
(Others not tested)

**Comment by sorvell** [comment]
Placing `NodeParts` like you've done inside a `contenteditable` is not supported. This is because `lit-html` uses `Comments` to track where to update parts of the DOM. When editing a `contenteditable` it's really easy to delete these `Comments`. Doing so will generally cause `lit-html` to get very confused and throw an exception.

There are a couple of alternatives that I've shown here: https://stackblitz.com/edit/js-zeyptr. The easiest workaround is to use a property binding to `.innerHTML` instead of using a `NodePart`.

```
<div
  contenteditable
  .innerHTML=${data.edit ? data.formatter : data.label}
></div>`
```

I went ahead and showed how you could keep the user entered value in sync (seems like you'd probably want that), and there's also an imperative version showing you can do just the manipulations of the contenteditable manually (as might have already been obvious).

Hope that helps.

**Comment by hokiedsp** [comment]
@sorvell - Thank you so much for the solution!!

I knew my code was interfering with lit-html's comments, and shame on me for not to think of using `.innerHTML`
