### ISSUE TITLE
Question: Does `html` take fragments as arguments?

### ISSUE THREAD

**Issue by timonson** [Polymer/lit-html#1175]
I could not find the answer anywhere. Unfortunately the type of the `values` parameter of `TemplateResult` is `values: readonly unknown[];` and is not really self-explanatory. Therefore I am not sure if I can pass DOM fragments to the `html` function although I know that it works. But I would like to ask if this could somehow cause problems.

Example:

```typescript
function createHtmlTemplate(html: string) {
  var template = document.createElement("template")
  template.innerHTML = html.trim()
  return template
}

html`${createHtmlTemplate(`<p>Hello World</p>`).content}`
```

Is this a valid way to use `html`? 

Thank you!

**Comment by justinfagnani** [comment]
You can use DOM Nodes as values as documented in the supported data types section: https://lit-html.polymer-project.org/guide/template-reference#supported-data-types-for-text-bindings

Passing a Node will insert that node into the DOM, so make sure that the semantics of that are what you want. In the case of a `<template>` element, inserting the element itself will not cause anything to render because the template contents are stored as a separate document fragment. You probably want to return `template.content`.

You seem to be basically re-implementing `unsafeHTML` without the dirty-checking though. WHat's your use case?

**Comment by timonson** [comment]
@justinfagnani thank you. I have one quick follow-up question before I close this issue: Do SVGs fall under DOM Nodes here?
