### ISSUE TITLE
Sanitise href attribute

### ISSUE THREAD

**Issue by weiwei-lin** [Polymer/lit-html#1196]
# Description
href attributes are not sanitised.

# Steps to Reproduce

1. Write this code

```ts
import {html, render} from 'lit-html';

render(html`<a href="javascript:alert(document.domain)">link</a>`, document.body);
```

2. See this output...

## Live Reproduction Link
https://stackblitz.com/edit/lit-html-ekzlne

## Expected Results
the URL should be sanitised.

## Actual Results
Clicking on the link, javascript will be executed

## Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

**Comment by grimly** [comment]
I would expect what you see. 

In a template literal, it should be expected because your application should run trustable code.
Keep in mind a template literal cannot be changed on runtime (they are frozen read-only arrays)

What instead might be an issue would be this code : 

```typescript
html`<a href="${'javascript:alert("hello")}>click me</a>`
```

But on this one you can do it yourself by providing your own `TemplateProcessor`.

**Comment by justinfagnani** [comment]
We had work on a sanitization hook system, but didn't release it because of the size impact it had and how close TrustedTypes was to shipping. Now that TrustedTypes is shipping in Chrome and hopefully other browsers soon, we think this is the way forward. Already you can enable CSP to reject `javascript:` attributes and inline script. Enable TrustedTypes would do this as well, and from there you can create a policy to sanitize these types of inputs and pass a trusted value to the lit-html template if it passes.

See this article: https://web.dev/trusted-types/

**Comment by justinfagnani** [comment]
Closing to dedupe with https://github.com/Polymer/lit-html/issues/1271
