### ISSUE TITLE
Question: Import ts instead of js

### ISSUE THREAD

**Issue by timreichen** [Polymer/lit-html#1200]
lit-html imported ```.js``` files  do not exist before transpiling. Tools like Deno allow direct url imports (js and ts). At the moment, lit-html breaks that great feature, especially with path resolutions of directives.
Any plans on fixing that so lit-html sources can be used directly?

**Comment by justinfagnani** [comment]
We publish pre-build JavaScript to npm. Just use that.

More detail: When tsc compiles files, they are output with .js extensions. Those file actually exist and can be requested by browsers and served by servers. IOW, our package contents are standard JS that loads correctly today in all browsers.

If Deno has a problem loading the JavaScript files, that would be a Deno bug.

**Comment by timreichen** [comment]
Thank you for your answer. Deno doesn't have problems with loading js files.
I meant that it could take ts files instead of js if the paths would be ```.ts``` instead of ```.js```.
Example:

```ts
deno bundle https://raw.githubusercontent.com/Polymer/lit-html/master/src/lit-html.ts
```

This doesn't work at the moment because the import file ```'./lib/default-template-processor.js'``` doesn't exist, only after transpilation.
Could the import not be ```'./lib/default-template-processor.ts'```  all imports point to actual files and doesn't tsc replace ```.ts``` to ```.js``` for imports anyway when transpiled?

**Comment by justinfagnani** [comment]
The only reason we publish the .ts files is for sourcemaps. We only support importing the .js files, otherwise there could be duplicate definitions of everything based on how you import them. Deno should hopefully support loading the .js files.

The reason why we include the .js file extension is that tsc oes not modify the specifiers at all. They need to work after compilation, so they need to refer to the files produced by compilation. tsc maps imports of .js files to the .ts file that generates it. Deno should support that style too. If they don't, then you can't write TS source that works both in Deno and in tsc/browsers.

**Comment by justinfagnani** [comment]
Closing as we really only support importing the .js modules. Hopefully there's no particular upside to importing .ts fines in Deno, as we also publish the types. Importing .js will save Deno from having to compile anything.
