### ISSUE TITLE
[lit-html] Finalize public Part API

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#1261]
We've created the PartInfo interface as a common interface between client-side and server-side Parts. Now we need to finalize the client-side only public interface, especially `__value` and `__setValue`.

`__value` is currently used by `live()` in order to bypass the dirty-checking of `__setValue()`. We thought we might not need `__setValue()` because we can return values from directives now, but it's used by `repeat()` to set item part values, and it'll be needed by any action-at-a-distance directive that doesn't integrate with a host element, like `until()`, `asyncReplace()`, and some localization directives. Without it those are unimplementable, possibly hindering upgrade paths even if we don't include them in core anymore.

**Comment by kevinpschaaf** [comment]
A couple other notes I've made for things we should be sure to work out as part of finalizing the API:
* `_$litType$` used by cache to determine if value is TemplateResult - need some sort of value type helper API?
* The meaning of "value": If we're going to keep around a public API for the "value" instance field (currently `__value` / `getPartValue`), I would love to call it something different.  The values you pass to update/`setValue` have a different meaning than `__value`, so they should have different names IMO. The value stored in `__value` is after any transformations during commit (resolving directive, turning TemplateResult into TemplateInstance...), and is used for dirty-checking. Maybe `committedValue` or `resolvedValue`?
* Is `value.strings === undefined` going to be our official API for non-interpolated/full-width attribute bindings?
* Do we want to stick with long-ish `PROPERTY_PART`, etc. constants as the public API for differentiating `part.type`?
* Should `getLiveValue` be on `AttributePart` interface or a part helper function? Any other uses for that outside of `live`?
* Are we going to support async directives? This is possible for `NodePart` (given `setPartValue` helper), but not for `AttributePart`. Should we update `setPartValue` to do a good thing for `AttributePart` (or add an attribute-specific setter helper)?

These are more around directives, but might as well include here since they're inter-related:
* `update` / `render` - some directives have unused `render` - how should we/users test that (styleMap currently pulls off `result._$litDirective` and subclasses the directive class to actually use `render`)?
* Nested directives - in or out?

**Comment by justinfagnani** [comment]
Another need for a replacement for `instanceof TemplateResult`: https://github.com/open-wc/open-wc/pull/1851/files#r493625677

**Comment by kevinpschaaf** [comment]
A few more:

* Move `Directive` and `directive()` from core to a `directive.ts` module?
* Combine `directive.ts` module with `parts.ts` helpers into one module?
* Make `setDirectiveValue` an instance method on `Directive`?
