### ISSUE TITLE
Memory leak in `render.ts`

### ISSUE THREAD

**Issue by sedwards2009** [Polymer/lit-html#1416]
**Description & Analysis**

I've been hunting down memory leaks in my (Electron) application and I'm fair certain that I've identify one originating in lit-html.

The problem is the `parts` `WeakMap` in lit-html's `render.ts` file. If the `container` node is removed from the DOM by the application, then the `parts` `WeakMap` will keep a reference to it and keep it alive including any parent, sibling, and child nodes attached to `container`. The `WeakMap` has a weak reference to `container` via the key, but it also holds an indirect  strong reference to `container` via the value in the map itself.

The "loop" looks like this:

* The `parts` `WeakMap` has a mapping with key=`container` to value=`NodePart` instance.
* This `NodePart` has `startNode` and/or `endNode` fields which reference a node.
* This node is a child of `container`, and therefore its `Node.parentNode` (and similar DOM properties) references `container`.

Thus keeping `container` and (the key in the `WeakMap`) alive. Remember, only the keys in a `WeakMap` are weakly held references.

I'm using lit-html to render the contents of custom elements. The whole custom element itself is created/destroyed via the DOM (and not lit-html). When this happens the small DOM subtree inside the element is kept alive by lit-html.

As a work-around I'm now using is to manually delete the entry in `parts`, i.e. `parts.set(container, undefined);`, and to also manually break all of the parent/child links inside a DOM subtree when I don't want it anymore.

This problem with `WeakMap` may occur elsewhere in lit-html. (I found the exact same problem in my app!)

A solution may be to add some kind of `dispose(container)` function, or to remove `startNode` and `endNode` in `NodeParts` and to search for those nodes directly but not to keep a direct reference.

With all that said, I do enjoy using lit-html!

**Related issues**

This issue is similar to issue: #342

**Version**

lit-html version 1.2.1

**Comment by kevinpschaaf** [comment]
Thanks for the writeup here. We did some investigation into this issue, and didn't come to the same conclusion: once the references to the `container` key of the WeakMap are retained only via the `value` (and there are no other paths to `container` except by starting at the `value`), we confirmed that the `WeakMap` can and does GC the `NodePart`.

This is consistent with the [spec text here](https://tc39.es/ecma262/#sec-weakmap-objects) (where the bolded text can be read as confirming that a reference to the key only via the value held in the WeakMap is not sufficient to keep the key deemed "accessible"):

> WeakMap and WeakSets are intended to provide mechanisms for dynamically associating state with an object in a manner that does not “leak” memory resources if, **in the absence of the WeakMap or WeakSet**, the object otherwise became inaccessible and subject to resource reclamation by the implementation's garbage collection mechanisms. 

Here's a minimal repro that I believe should exercise the leak if your suspicion about circular references between the key and value of a WeakMap were true: https://jsbin.com/jaqowor/edit?html,output

Running this repro, we see periodic GC's reclaiming the nodes that were created in the part:

![image.png](https://images.zenhubusercontent.com/5afdd6514b5806bc2bd39b97/7e9d0dcd-930e-47cc-8b19-f56cadbc3a78)

Due to the nature of WeakMaps, it is impossible to observe the contents of a WeakMap to confirm whether it's GC'ed (and although I don't have first-hand knowledge, I don't trust that devtools's ability to print the contents of a WeakMap doesn't alter its GC behavior), so heap measurement/snapshotting is the safest to confirm what's going on, and I this this demonstrates the circular reference does not seem to trip up the GC-ability of the WeakMap values.

If you can alter the repro above to demonstrate a leak, we'd be happy to look into this more.

**Comment by sedwards2009** [comment]
Thank you for digging into this so thoroughly.

I've going through my application recently and fixed a lot of possible leaks which are not related to lit-html. I just did some tests with my lit-html work around removed to see what happens, and it does agree with your WeakMap analysis above. So, that's a job well done on your side :champagne: and I've learned some more subtleties about WeakMaps. :-)

Thanks again for your effort on this.
