### ISSUE TITLE
[QUESTION] How to use ShadyDOM in with lit-html? (error: ShadyDOM['patch'] is not a function)

### ISSUE THREAD

**Issue by coen22** [Polymer/lit-html#1436]
I've been trying to move from Polymer 3 to lit-html using the open-wc template, but I'm running into some issues. To be able to use the browser's autocomplete features, my application can't use the ShadowDOM. Safari and Chrome won't fill in passwords that way (Although Firefox does). When using Polymer, I was using the following in the index.html to fix that issue:

```
ShadyDOM = { force: true };
ShadyCSS = { shimcssproperties: true};
```

In lit-html, I see that there is a shady-render lib which is also used, but I still see Shadow Content in the DOM tree. Trying to set `window.ShadyDOM = { force: true }` only causes some errors. I changed it to the following:

```
window.ShadyDOM = {
    force: true,
    prepareTemplateDom: true
};
``` 

This works when building and starting (`npm run start:build`), but not during development (`npm run start`). The latter results in the following error: `ShadyDOM['patch'] is not a function. (In 'ShadyDOM['patch'](n)', 'ShadyDOM['patch']' is undefined)`. 

What does this method need to be?
Or is there another solution for this?

**Comment by sorvell** [comment]
Sorry for the trouble, but you're headed in the right direction. Some typical issues we've seen people encounter:

1. Loading an older version of webcomonentsjs. Make sure to update this to the current version
2. Setting the `ShadyDOM` object after loading the polyfill scripts instead of before. Note, you should only need `window.ShadyDOM = {force: true}`

Here's a working version for reference: https://stackblitz.com/edit/lit-element-demo-k4ccnl?file=index.html.

Hope that helps.

**Comment by coen22** [comment]
I found out that when building with rollup the webcomponentjs loader is included whereas with a normal run, I'm not loading any polyfils and therefore those settings don't get picked up.
