### ISSUE TITLE
[labs] Add reactive controller -> hooks adapter to labs

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#1531]
Some subset of reactive controllers will depend only on the generic ReactiveControllerHost interface and not specifics of that host being a LitElement. These types of controllers can probably be wrapped into React hooks, making them a lower-level primitive for code sharing across frameworks and web components.

To make a hook wrapper we need to create and store a controller instance with `useState`, trigger the controller lifecycle via the built-in React hooks, and possibly allow mapping any OOP (property/method) APIs on the controller to hook function arguments and return values for more idiomatic hooks.

**Comment by justinfagnani** [comment]
cc @Westbrook and @benjamind if you have any ideas for a type of controller to make sure works with this pattern, let us know!

**Comment by devongovett** [comment]
Following along here. Just thought I should note one thing you'll need to watch out for in the React wrapper: concurrent mode. It's not safe to mutate objects used in React components, especially in concurrent mode, as multiple versions of a component tree may be active at a time. I think either immutable state will need to somehow be stored in `useState` rather than as instance properties on the controller class, or perhaps something with [useMutableSource](https://github.com/reactjs/rfcs/blob/master/text/0147-use-mutable-source.md), though I haven't looked too deeply into that myself. Looks like it might require some kind of deep clone, however, which would probably be expensive.

**Comment by justinfagnani** [comment]
Thanks for the pointer to useMutableSource!

Snapshotting looks like a complication, but maybe tractable much of the time. Most controllers will be simple class instances: just instance properties + a prototype. Cloning/snapshotting those will not inherently be more expensive than any other object. I suspect that most complications in snapshotting are going to be around libraries the controllers wrap, ie if you use a spring library it has to have cloneable spring state (though I suspect it's not worth worrying about in some cases because tearing either isn't noticeable, or the tearing behavior is arguably more correct).

It seems like the most general approach is going to involve letting the hook wrapper call customize the behavior: map arguments to ctor arguments or instance calls, map the instance to a return value, and potentially get a snapshot or something even more general than that that would let the author bring their own strategy - iow, not bake in useMutableSource support directly.
