### ISSUE TITLE
[lit-next] Consider making controller directives easier to implement

### ISSUE THREAD

**Issue by sorvell** [Polymer/lit-html#1546]
## Description
Currently the `ReactiveController` and `Directive` APIs collide slightly and this makes using a `Directive` as a controller slightly cumbersome as a separate object must be the controller. This collision is on `disconnected` and `update`.

|API                      |ReactiveController|AsyncDirective|
|----------------|-------------------|---------------|
|`connected`      | ✅                            |                          |
|**`disconnected`** |✅                             |✅                       |
|`reconnected`  |                                |✅                       |
|`willUpdate`      |✅                             |                          |
|**`update`**     |✅                             |✅                        |
|`updated`          |✅                             |                          |
|`render`             |                                |✅                       |
|`setValue`          |                                |✅                       |

Some possibilities: 
* one of the objects could use the `Callback` suffix
* Directive could use `activate`/`deactivate` instead of `disconnected`/`reconnected` and `commit` instead of `update`.

## Acceptance criteria
Decide on new names and implement changes.

**Comment by justinfagnani** [comment]
It would be really great, IMO, if the current name collisions weren't disambiguated, but made compatible instead.

For `disconnected` there shouldn't be a case where `ReactiveController.disconnected` is called but `AsyncDirective.disconnected` isn't, so `AsyncDirective.disconnected` is a superset with more specific timing. Could we make it so that `disconnected` is just only called once when a host disconnects? Similarly for `update`.

I haven't thought much how this might be done, or if it's feasible. `disconnected` might work out already if `AsyncDirective.disconnected` calls `removeController`. `update()` is hard because we don't know for sure that a directive `update` will be called (say if it's in a guard).

**Comment by sorvell** [comment]
> It would be really great, IMO, if the current name collisions weren't disambiguated, but made compatible `instead.`

I don't think that makes sense for `update`. The `Controller.update` and `Directive.update` are just conceptually different.

**Comment by sorvell** [comment]
After an offline chat, we've decided to add a `host` prefix to the callbacks in ReactiveControllers.

* `hostConnected`
* `hostDisconnected`
* `hostWillUpdate`
* `hostUpdate`
* `hostUpdated`

**Comment by sorvell** [comment]
Fixed via #1553.
