### ISSUE TITLE
[lit-next] Short license headers breaks tests due to reposition of null byte

### ISSUE THREAD

**Issue by aomarks** [Polymer/lit-html#1633]
https://github.com/Polymer/lit-html/pull/1630 replaces our license statements with the newly approved SPDX short style.

I had trouble believing that a shorter license statement could break all our tests, but it happened. 

## What happened

`lit-html.js` contains the following lines:

  ```ts
  const NAME_CHAR = `[^\0-\x1F\x7F-\x9F "'>=/]`;
  ```

  ```ts
  const tagEndRegex = new RegExp(`>|${SPACE_CHAR}(?:(${NAME_CHAR}+)(${SPACE_CHAR}*=${SPACE_CHAR}*(?:${ATTR_VALUE_CHAR}|("|')|))|$)`, 'g');
  ```

   https://github.com/Polymer/lit-html/blob/lit-next/packages/lit-html/src/lit-html.ts#L140

With unsafe optimizations on, Terser minifies the `\0` escape sequence to an actual null byte, as part of its RegExp constructor optimization:

  ```js
  const _ = new RegExp(`... ?:($<NUL>+...`)
  ```

*By shortening the copyright header, we moved the null byte closer to the beginning of the file.*

Now, some code path in @web/dev-server (Koa static middleware?) begins setting the response body as a Buffer instead of a string. My guess is that there's some charset sniffing logic which looks at the first N bytes. It doesn't think `0` is a valid UTF-8 byte, so it doesn't automatically decode to a string.

The @web/dev-server module transform middleware assumes string bodies (no thanks to the type for Koa `context.body` being `any`), so it passes this Buffer to es-module-lexer, which then throws because it expects a string.

## Thoughts

I noticed that VSCode and Meld also freak out when they see it early in the file. VSCode prompts if you want to open a binary file. Meld sniffs the file as UTF-16, and if you force UTF-8 it says it has substituted an invalid character.

Interestingly, Terser only emits the null byte as part of its RegExp constructor optimization:

  ```sh
  # Escaped
  echo 'console.log(`\0`)' | terser -c unsafe | hexdump -c
  
  # Null byte
  echo 'console.log(new RegExp(`\0`))' | terser -c unsafe | hexdump -c

  # Hex escape instead of octal doesn't make any difference
  echo 'console.log(new RegExp(`\x00`))' | terser -c unsafe | hexdump -c
   ```

Seems like Terser probably shouldn't emit null bytes, so I filed terser/terser#942.

Also, @web/dev-server shouldn't assume response bodies from upstream middleware will always be strings.

## Ideas

1. We could just fix the @web/dev-server bug (I have a PR ready) to unblock our tests. However, given what I saw with e.g. VSCode not believing this to be a UTF-8 file, I think we should avoid publishing the null byte. Other tools/servers might have issues with it, plus it's weird for users to not be able to open it without a warning in VSCode.

2. We could change the Terser settings just for `lit-html.js`, but we'll get a small size bump:
  Disabling `unsafe` optimizations increases size of `lit-html.js` from 6.31 KB raw / 2.60 KB brotli (from 6.27 / 2.58).
  Enabling `ascii_only` increases size to  6.33 / 2.61.

3. We could re-arrange the file so that the `NAME_CHAR` const appears somewhere further into the file. (Too brittle, could regress in the future, plus some tools might care about a null byte *anywhere* in the file.)

4. We could change the `NAME_CHAR` regex fragment to not worry about null, and switch from `\0-\x1F` to `\x01-\x1F`. The purpose of the regex is to detect attribute names, and this fragment is there to exclude control characters. So, this would make lit-html think a null character could be an attribute name. Seems super rare this would ever come up in practice, but I don't think we want to introduce the possibility.

5. We could do a post-Terser substitution of the null byte back to an escape sequence. This seems pretty good, except that if anybody else minifies our published `lit-html.js` with unsafe optimizations, the same thing will happen. If Terser also changes the behavior soon, though, this seems fine.

**Comment by justinfagnani** [comment]
This is wild. I like option (4), but I'd go even further. These regexes are derived from the HTML spec, but I'd almost guarantee that the control characters are never encountered in the wild, and we certainly don't cover them in tests.

I'd be willing to go off-spec completely regarding control characters, and have wanted to try that for a while (see my TODO).

So we could go from this:

```ts
// TODO (justinfagnani): can we get away with `\s`?
const SPACE_CHAR = `[ \t\n\f\r]`;
const ATTR_VALUE_CHAR = `[^ \t\n\f\r"'\`<>=]`;
const NAME_CHAR = `[^\0-\x1F\x7F-\x9F "'>=/]`;
```

to:
```ts
const SPACE_CHAR = `\\s`; // to be inlined
const ATTR_VALUE_CHAR = `[^\\s"'\`<>=]`;
const NAME_CHAR = `[^\\s"'>=/]`;

```

Our space character class would change to accept other unicode spaces: `\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff`. This means that our scanner would diverge slightly from the HTML parser and treat those characters as ending an attribute name or an unquoted attribute value. The scanner could then add a binding for the wrong attribute name, which might not be the end of the world.

A test for what would happen would look like:

```ts
test('weird spaces', () => {
  // I thought this is what would happen, but we actually get an exception
  assertRender(html`<div a\u00a0b=${'A'}></div>`, '<div a="" b="A"></div>');
  assertRender(html`<div a=${'A'}\u00a0${'B'}></div>`, '<div a="A"></div>');
});
```

Right now we throw because we're looking up the wrong attribute name. Throwing on characters we don't handle well is arguably better than subtly different behavior, so maybe that's ok.

**Comment by justinfagnani** [comment]
So it turns out that we don't support binding to attribute names with unicode spaces already. `setAttribute()` has a different definition of valid attribute names than HTML (which is why we use the `.`, `@`, and `?` prefixes - they don't work with `setAttribute()`) and it throws when binding to them.

So
```ts
`html`<div a\u00a0b=${'A'}></div>`
```
is already not working and we would just throw in a different spot.

That leaves cases like:

```
html`<div a=${'A'}\u00a0${'B'}></div>`
```

which currently renders to `<div a="A&nbsp;B"></div>` but renders to `<div a="A&nbsp;B1"></div>` if we use `\s`. This is because we think the second binding is an element position binding during marker insertion, but we do see it as an attribute binding when walking the template tree.

`\u00a0` in particular is pretty useful, corresponds to an HTML entity, and may end up being in source, so a middle ground from using `\s` everywhere could be to just use it in the `NAME_CHAR` class:

```ts
const SPACE_CHAR = `[ \t\n\f\r]`;
const ATTR_VALUE_CHAR = `[^ \t\n\f\r"'\`<>=]`;
const NAME_CHAR = `[^\\s"'>=/]`;
```

**Comment by aomarks** [comment]
Filed https://github.com/terser/terser/issues/942 since I think, regardless of our solution, Terser probably shouldn't be emitting null bytes here.

**Comment by aomarks** [comment]
Fixed by https://github.com/Polymer/lit-html/pull/1635
