### ISSUE TITLE
[reactive-element] Pass changedProperties to controller hostUpdate / hostUpdated

### ISSUE THREAD

**Issue by web-padawan** [Polymer/lit-html#1758]
# Description

Currently there is no way to get the `changedProperties` map in the controller because they are not passed there:

https://github.com/Polymer/lit-html/blob/4ea50304225b386fa50a42c4b77554812c14ac67/packages/reactive-element/src/reactive-element.ts#L1062

https://github.com/Polymer/lit-html/blob/4ea50304225b386fa50a42c4b77554812c14ac67/packages/reactive-element/src/reactive-element.ts#L1089

Is that by design to make the API implementation-agnostic? Or is this something that could be added?

**Comment by justinfagnani** [comment]
This is left out intentionally for two reasons:

1) Interop: We'd like reactive controllers to be able to work across different frameworks, and not all frameworks track per-property changes like ReactiveElement does. React certainly doesn't.
2) Coupling. Having access to `changedProperties` encourages much tighter coupling between the controller and the element, where the controller might only work with elements that have certain named properties. This could create situations where two controllers can't work on the same element because of a conflict over a host property name.
3) Composition. We want to enable composing multiple controllers together within a host to create more complex behaviors. This might involve the host passing new values from one controller to another, rather than the controller receiving them from the host. `changedProperties` discourages that modularity.

In general I think there are better ways to get new properties into a controller. A pull-based approach, like we've implemented in `Task` and is common in React hooks like `useEffect`, is to provide a deps function:

```ts
  private _myController = MyController(this, () => [this.foo, this.bar]);
```

The controller can then pull new deps in `hostUpdate()`. This allows for passing in values that are not host properties, like globals or values from other controllers.

A push-based is good for chaining:

```ts
render() {
  this._myController.input = this.foo;
  this._myController2.input = this._myController.output;
}
```

**Comment by justinfagnani** [comment]
@arthurevans there's definitely room for a lot more advice on controller like this ^

**Comment by web-padawan** [comment]
Thanks for the detailed explanation!
