### ISSUE TITLE
repeat does not seem to handle promises properly

### ISSUE THREAD

**Issue by depeele** [Polymer/lit-html#193]
I'm trying to use `repeat` in the following manner:
```
html`
<ul>
  ${repeat( this.getAccounts(), (account) => html`
    <li data-id="${account.id}">${account.name}</li>
  `)}
</ul>
`;
```

The `getAccounts` method has the form:
```
getAccounts() {
  return this.collections.account.find();
  // returns a Promise which resolves with an array of items
}
```

When trying to use code of this sort, `repeat()` complains about non-iterable values and never performs the desired repetition. It seems to be taking the provided items and then attempting to iterate over them directly.

I would propose an update to `repeat` along the following lines:
```
...
return directive( async (part) => {
  const resolved = (items instanceof Promise
                                ? await items
                                : items);
  ... using `resolved` in place of `items` ...
});
```

**Comment by TimvdLippe** [comment]
If the function returns a promise, I would expect the await to be placed outside of the repeat like:
```js
html`
<ul>
  ${repeat(await this.getAccounts(), (account) => html`
    <li data-id="${account.id}">${account.name}</li>
  `)}
</ul>
`;
```

That would work as well right?

**Comment by bgotink** [comment]
Alternatively a promise could be passed with `repeat` in the `then`:

```js
html`
<ul>
  ${this.getAccounts().then((accounts) => repeat(accounts, (account) => html`
    <li data-id="${account.id}">${account.name}</li>
  `))}
</ul>
`;
```

This has the added benefit of allowing `until` to be combined with it.

**Comment by justinfagnani** [comment]
There are a number of ways you'd want to compose async values and various directives. Ideally every directive could accept both Promises and Async Iterables for any argument. Because expressions are just JS, we can't really do magic to make that happen, but we could offer helpers for writing directives.

What we really want here is conceptually a lift operation that turns a template with async values into something of an async function itself... so that expressions within the template don't have to deal with asynchronicity. We can't exactly do that (we could if we had our own expression interpreter), but maybe we can make it _look_ like that most of the time. I'm going to think on this...

**Comment by depeele** [comment]
@TimvdLippe when I try using `await` in this way, I get a `SyntaxError`.
@bgotink this does work but seems overly complex.

@justinfagnani would something along the lines I proposed provide the sort of helper you are suggesting. Perhaps something like:
````javascript
function async resolveAsync( val ) {
  const resolved = (val instanceof Promise
                                ? await val
                                : val);
  return resolved;
}
````

Using this, directives like `repeat` could become:
```javascript
function repeat(items, keyFnOrTemplate, template) {
  ...
  return directive( async (part) => {
    const resolved = resolveAsync( items );
    ... using `resolved` in place of `items` ...
  }
}
```

**Comment by bgotink** [comment]
In the example `repeat` function, the result of `resolveAsync(items)` is always a promise, so all calls to repeat become asynchronous even if the parameters aren't.

As an alternative solution I suggest introducing an `asyncable` function which wraps around a function and does the following: if any of the parameters to the function are promises, await those promises and then call the wrapped function with the resolved values, otherwise simply call the wrapped function with the values.
In other words: stay synchronous unless any of the parameters are asynchronous.

This allows for:

```ts
const repeat = asyncable(function (items, keyFnOrTemplate, template) {
  // if items, keyFnOrTemplate and template were promises, asyncable will have resolved them for us
  // this function _never_ gets a promise as parameter
  return directive((part) => {
    // ... just use items here
  }
});
```

I quickly put together a simple `asyncable` function which supports asynchronous thenables, synchronous thenables and regular values:

```js
function asyncable(fn) {
  return function(...args) {
    const resolvedArgs = [];
    const promises = [];
    
    for (let i = 0; i < args.length; i++) {
      const arg = args[i];
      if (typeof arg === 'object' && typeof arg.then === 'function') {
        let resolved = false;
        const promise = arg.then(val => {
          resolvedArgs[i] = val;
          resolved = true;
        });
        if (!resolved) {
          promises.push(promise);
        }
      } else {
        resolvedArgs[i] = arg;
      }
    }

    if (promises.length) {
      return Promise.all(promises).then(() => fn.apply(this, resolvedArgs));
    } else {
      return fn.apply(this, resolvedArgs);
    }
  }
}
```

**Comment by justinfagnani** [comment]
Closing now. Most APIs do not seamlessly accept Promises. You can use JS and the forthcoming `async()` directive to explicitly handle async values.
