### ISSUE TITLE
Lit printing `{{lit-*}}` instead of value.

### ISSUE THREAD

**Issue by gauntface** [Polymer/lit-html#257]
For some reason, lit is returning it's own placeholder and mis-placing the values - the h6 `disabled` value should be where the `{{lit-***}}=""` should be.

```html
  <div class="org-webhook-item">
    <input class="org-webhook-item__toggle" type="checkbox" {{lit-14022481768476736}}="">
    <div class="org-webhook-item__details">
      <h6> disabled</h6>
      <p>TODO: Add state message</p>
    </div>
  </div>
```

Code resulting in this is:

```javascript
function hookTemplate(org: OrgWebHookState) {
  return html`
  <div class="org-webhook-item">
    <input class="org-webhook-item__toggle" type="checkbox" ${org.viewerCanAdminister ? 'test' : ' disabled'}></input>
    <div class="org-webhook-item__details">
      <h6>${org.name}</h6>
      <p>TODO: Add state message</p>
    </div>
  </div>`;
}
```

**Comment by justinfagnani** [comment]
It looks like you're trying to dynamically choose the name of an attribute here:

```js
html`
  <input class="org-webhook-item__toggle" type="checkbox" ${org.viewerCanAdminister ? 'test' : ' disabled'}>`
```

That's not something lit can currently do. Expressions are only valid in attribute value position, not attribute name position. When expressions are replaced by placeholders before HTML parsing, you'll get this result where the placeholder is parsed as an attribute name. And because there's one placeholder text globally, we can't just look for that as an attribute name to make it dynamic, because if there were multiple dynamic attribute names, they'd use the same placehold and be folded into the same attribute by the DOM.

The eventual solution here is in #213 which will allow for spread expressions, so you can do:

```js
html`
  <input 
      class="org-webhook-item__toggle"
      type="checkbox" 
      ...=${[org.viewerCanAdminister ? 'test' : ' disabled']: ''}>`
```

^ that's an object literal with a computed property key.

I'll get #213 moving.

**Comment by daKmoR** [comment]
Maybe, in this case, a better approach would be using https://github.com/Polymer/lit-html/pull/197. You would end up with something like this...
```
<input type="checkbox" disabled?="${org.viewerCanAdminister}"></input>
```
Still also not possible in the current master...

so it appears you will have to wait... but 2 approaches are already in the works so fingers crossed it will be possible pretty soon :)

**Comment by justinfagnani** [comment]
I just added #259 which is very much like #197, and I think we can get it merged asap for a release this week.

**Comment by justinfagnani** [comment]
Deduping all boolean/conditional attribute issues to #56

**Comment by gauntface** [comment]
@justinfagnani is there a way to catch this situation and throw an error?

**Comment by justinfagnani** [comment]
@gauntface probably not easily.

We construct a string as pass it to `template.innerHTML`, which never throws following the HTML 5 parsing algorithm. To know the real syntactic position of an expression we'd have to do parsing ourselves, which we avoid for speed and size. We guess at the position in a couple of a places with regexes, but it's not perfect and assumes that expressions are in text or attribute value position to begin with.

Linting is the best bet here I think.
