### ISSUE TITLE
Render *just* a templateResult that is rendered in a larger TemplateResult

### ISSUE THREAD

**Issue by gauntface** [Polymer/lit-html#289]
One thing I'm struggling to figure out with lit is if I have a template that is embedded in another template, how can I update the rested template?

For example, the top level might be:
```javascript
import {someTemplate} from '../somewhere';

const mainTemplate = html`Hello ${someTemplate('world')}`;
render(mainTemplate, document.body);
```

Then in someTemplate, we could have:

```javascript
const currentColor = 'red';
export function someTemplate(name) {
   return html`<div class$="${currentColor}">${name}</div>`;
}

export function setColor(color) {
    currentColor = color;
    // TODO: Update the render of someTemplate.
}
```

At the moment it seems like I'd need to re-run the `render()` and there is no way for this component to re-render itself. Is that the case?

p.s. The example I'm currently trying to implement is list that expands / shrinks.

**Comment by justinfagnani** [comment]
I think @obedm503 is right here. It looks like you're trying to make a component, so I'd use a component model like Web Components. Polymer's base class for that is here: https://github.com/PolymerLabs/lit-element

It's important to note that there is no instance of anything for `setColor` to act on. `someTemplate()` may have been rendered into multiple places, multiple times. Each render creates a new TemplateResult, but there's no telling whether that's a re-render or new render, so there would be no option but to set the color globally.

If that's ok, you _might_ be able to bind to an async iterator rather than a simple value.
