### ISSUE TITLE
UnsafeHtml + DataBinding ?

### ISSUE THREAD

**Issue by robrez** [Polymer/lit-html#292]
We have a use-case where templates are obtained from the server.  I was trying to replace Polymer.Templatize with lit html. eg:

#### Polymer.Templatize
```javascript
let template = "<div>Hello [[name]]</div>";
let domTemplate = document.createElement("template");
domTemplate.innerHTML = template;
let tClass = Polymer.Templatize.templatize(domTemplate, owner);
let tInstance = new tClass({ name: "Fred" });
console.log(tInstance.root.outerHTML);
```

Output:  `<div>Hello Fred</div>`

#### Lit Attempt
```javascript
let template = "<div>Hello ${name}</div>";
let templateResult = (name) => html`${unsafeHTML(template)}`;
let el = document.createElement("div");
render(templateResult('Fred'), el);
console.log(el.innerHTML);
```

Output:  `<div>Hello ${name}</div>`

Is this something that Lit html will support?

**Comment by justinfagnani** [comment]
lit-html relies on JavaScript itself to parse the templates into literal and dynamic parts. It can't create a template literal as that's JavaScript source. The best you can do is something with `eval()` or `new Function()`, like:

```ts
import {render, html} from 'lit-html/lib/lit-extended.js';

function makeTemplate(content: string) {
   // TODO: decode the template to handle escape sequences, etc.
  const templateContent = `return html\`${content}\`;`;
  // You may want to accept more arguments here for your data model,
  // or call with Function#call to set `this`:
  return new Function('html', templateContent).bind(undefined, html);
}
const template = makeTemplate('<div>Hello ${this.name}</div>');
const el = document.createElement("div");
render(template.call({name: 'Fred'}, el);
```

In general, this isn't a particularly great approach because you're dynamically evaluating code which can be a security nightmare and against most CSP policies. It also requires a lot of JavaScript in your templates, which if they're being stored in a database might be coming from a CMS or non-developers. 

The advantage of lit-html is that the expressions are just JavaScript in the same lexical scope as your template definition. If you're not defining templates in JS where you're using them, I think you lose a lot of the benefits. Templatizer is just fine for this use case.

**Comment by robrez** [comment]
Thanks for the info
