### ISSUE TITLE
Please throw on bad input

### ISSUE THREAD

**Issue by gauntface** [Polymer/lit-html#303]
It's easy to get in a situation where the template breaks, removing classes and it's unhelpful as it ultimately suppresses the issue.

for example:

```javascript
html`<div class="test ${foo ? 'bar': 'baz'}"></div>`
```

will result in:

```html
<div></div>
```

**Comment by justinfagnani** [comment]
What about

```js
html`<div class="test ${foo ? 'bar': 'baz'}"></div>`
```

breaks?

**Comment by gauntface** [comment]
In lit-extended it requires the dollar to work `class$="test ${foo ? 'bar' : 'baz'}"`

So less a case of throwing on bad input I guess and more throwing when lit is not going to parse an attributes value

**Comment by justinfagnani** [comment]
Ah, yes, lit-extended treats this as setting the _property_ `class`.

I'm not sure what we can do here. How would lit know that's a mistake?

**Comment by gauntface** [comment]
If lit see's a property or attribute in the input, and spits out something that doesn't have that property - that seems like something isn't right.

Essentially, your confusion at the start of this issue was the same confusion as mine when working with lit :(

**Comment by Lodin** [comment]
@gauntface Lit is not able to recognize if it is a property or an attribute, does property/attribute exist or not, because it knows nothing about elements you use. Especially if they are custom elements. Because everything lit does is looping through properties/attributes, determine which has `$` in it and apply following rule for each of them:
```javascript
// for attribute
element.setAttribute('attibuteWith$', value);

// for property
element[propertyWithout$] = value;
```
