### ISSUE TITLE
`repeat` Should warn on duplicate ids

### ISSUE THREAD

**Issue by bennypowers** [Polymer/lit-html#362]
# Given
```js
const do = render(html`${repeat(
  items,
  ({ id }) => id,
  ({ id }) => html`<span>${id}</span>`
)}, container)`;

do([{id: 1}, {id: 2}])
do([{id: 1}, {id: 2}, {id: 1}])
```

# I'd Expect 
- Warning logged to console
- `container.innerText === '21'` (this is less important than the warning)

# Instead
- No warning
- `container.innerText ===  '12'`

**Comment by kevinpschaaf** [comment]
In working on https://github.com/Polymer/lit-html/pull/501, I implemented a warning for duplicate keys. However, as part of performance-optimizing the repeat implementation, the bookkeeping cost just to record visited id's when such bookmarking is otherwise unneeded by the algorithm ended up being non-trivial and I removed it.  As a result, we opted to document the behavior of duplicate id's as "undefined", but not include a warning in the runtime code.

We could consider adding more runtime costly debug-mode checks like many other libraries do in the future, however we've avoided using the common `process.env` pattern thus far in order to keep our modules web-compatible.
