### ISSUE TITLE
Error after upgrading to latest version

### ISSUE THREAD

**Issue by quetzalsly** [Polymer/lit-html#364]
Getting this strange error after updating to the latest npm version (0.10.1) and (0.5.2) lit-element.

```
shady-render.ts:52 Uncaught TypeError: window.ShadyCSS.prepareTemplateDom is not a function
    at result (shady-render.ts:52)
    at render (shady-render.ts:150)
    at HTMLElement._applyRender (lit-element.ts:286)
    at HTMLElement._propertiesChanged (lit-element.ts:218)
    at HTMLElement._flushProperties (properties-changed.js:370)
    at HTMLElement._flushProperties (lit-element.ts:232)
    at HTMLElement.ready (properties-changed.js:193)
    at HTMLElement.ready (lit-element.ts:119)
    at HTMLElement._enableProperties (properties-changed.js:347)
    at HTMLElement.connectedCallback (properties-mixin.js:226)
```

**Comment by BrianDGLS** [comment]
I'm getting something similar.

```
Uncaught TypeError: Cannot read property 'prepareTemplateDom' of undefined
    at eval (shady-render.js:43)
    at render (shady-render.js:111)
    at HTMLElement._applyRender (lit-element.js:202)
    at HTMLElement._propertiesChanged (lit-element.js:151)
    at HTMLElement._flushProperties (properties-changed.js:341)
    at HTMLElement._flushProperties (lit-element.js:161)
    at HTMLElement.ready (properties-changed.js:185)
    at HTMLElement.ready (lit-element.js:83)
    at HTMLElement._enableProperties (properties-changed.js:321)
    at HTMLElement.connectedCallback (properties-mixin.js:209)
```

**Comment by BrianDGLS** [comment]
Running the same code on FireFox 60 gives the same error as @quetzalsly.

**Comment by AndreasGalster** [comment]
Same here. I think this is a typo. I just changed it to prepareTemplate (which works. sorta, though I still run into #43 after fixing the typo)

**Comment by AndreasGalster** [comment]
Mhh are you sure this is just webcomponents-loader issue? I am **not** using webcomponents-loader (no more polyfill at all) and it's breaking. (I am just trying the fix right now btw so if you've fixed it in general, sorry slow internet).

Just want to point this out :).

Also I noticed that lit-element hasn't received an update. I would assume the best way to use lit-element is to only install lit-element which lit-html as the correct dependency? Right now I would have to explicitly add lit-html with the upgraded version to try out your fix, since lit-element received no version bump.

**Comment by AndreasGalster** [comment]
This is still not working for me. Isn't it `window.ShadyCSS.prepareTemplate` instead of `window.ShadyCSS.prepareTemplate`?

**Comment by quetzalsly** [comment]
Still broken here, I am using the latest lit-element however, but had to roll back to version 0.10.0 for this library.

**Comment by AndreasGalster** [comment]
I'd like to point out I added latest webcomponents, lit-html and shady-css to dependencies, still failing for me. It's odd, I'm just not getting the prepareTemplateDom function on the window shady css object. Although there's definitely references in the code of the shady-css node_modules source code.

**Comment by sorvell** [comment]
Neither `lit-html` nor `lit-element` directly depend on `@webcomponents/webcomponentsjs` but *version 2.0.2* is required to work with the latest `shady-render`. For those having problems, please verify that you have this version or update to it if necessary. Thanks!

@AndreasGalster if you are using no polyfills, then the fix here is expected to make `shady-render` work, but I assume you're just doing that for testing since there's no reason to use `shady-render` without polyfills.

**Comment by AndreasGalster** [comment]
The problem is that shady CSS is pulled in from Polymer (I have a hybrid project), check out legacy-element-mixin line 10.

Also, despite having the version upgraded, I'm not getting prepareTenplateDom, which is very weird :/ it's in the source of the shady-css files

**Comment by davie-robertson** [comment]
My pwa-starter kit app has had this issue for a couple of days now. What are the steps to fix this - I seems to be using 5.2 and 10.2

**Comment by bennypowers** [comment]
I was able to work around this by installing `@webcomponents/shadycss@1.3.1`, then forced my bundler to override all references to that package with my top-level version. I'm using rollup, so I had to use [this patch file](https://pastebin.com/TNuyJ6mN) for `rollup-plugin-node-resolve`, and passed it these options:

```js
const jsnext = true;
const preferBuiltins = true;
const customResolveOptions = (options, id, importer) => {
  if (importer.includes('lit-')) options.basedir = __dirname;
  if (importer.includes('shadycss')) options.basedir = __dirname;
  if (importer === 'shaka-player') options.basedir = __dirname;
  if (importer.includes('graphql')) options.extensions = ['.js', '.json', '.node'];
};

const plugins = [
  resolve({customResolveOptions, jsNext, preferBuiltIns})
  ...plugins_
]
```

Ain't pretty, but seems to work.

**Comment by ernsheong** [comment]
I found the issue.

If you are running a hybrid Polymer 2 + LitElement app, upgrade your Polymer to 2.6.0 in `bower.json`. Earlier Polymer versions are pulling in older versions of `webcomponents/shadycss`. 😅
