### ISSUE TITLE
In inline/ternary ifs what is the optimal else?

### ISSUE THREAD

**Issue by KeithHenry** [Polymer/lit-html#395]
I have content embedded in a template I only want to render sometimes.

When *not* rendering with an inline ternary if, what is better to use?

```ts
// null
return html`...${boolProp ? html`...` : null }...`;

// undefined
return html`...${boolProp ? html`...` : undefined }...`;

// empty string
return html`...${boolProp ? html`...` : '' }...`;

// empty template
return html`...${boolProp ? html`...` : html`` }...`;
```

Which is best, or does it not matter?

**Comment by ruphin** [comment]
It makes no real difference. I prefer empty string, but you can use whatever notation you think is more clear.

Personally I tend to avoid conditional content in templates like this. They are more difficult to cache efficiently, and can cause random issues with ShadowDOM polyfills and inconsistencies with weird Web Compoment lifecycle timing.

For simple content I generally prefer to use a `display:none` toggle over conditional rendering:

```
return html`<div hidden?=${!boolProp}>...</div>`;
```

As long as you don't attach an obscene amount of DOM nodes or trigger a lot of scripts inside that conditional content, it doesn't add a lot of overhead as the browser will not perform any style or layout passes over hidden content. In my experience it costs virtually no additional loading time, but adds a lot of consistency.

This is an alternative the options you suggested that does have different performance characteristics.

**Comment by KeithHenry** [comment]
I've just used `boolProp` for these examples, in the context you describe I'd probably just `display:none;` too.

However, the pattern I have a lot of is objects:

```ts
return html`...${thing ? html`...${thing.foo}...${thing.bar}` : null }...`;
```

I realise this might be an anti-pattern, and I think it might be part of the cause of #397, but I'm not sure what to do instead.

**Comment by ruphin** [comment]
Have you tried not conditionally rendering these objects and placing them inside a hidden subtree?

```
return html`<div hidden?=${thing}>${thing.foo}...${thing.bar}</div>`;
```

From my experience, developers greatly overestimate the cost of basic operations like adding DOM nodes, and underestimate the cost of added complexity that comes with these conditional rendering systems. 

Until your application reaches a certain size, you are generally better off just rendering the entire app into the DOM and hiding the inert parts, however counter intuitive that seems. The only thing you need to be careful with is elements that initiate a lot of work or make AJAX calls when they are first created (which I consider an anti-pattern anyway).

If your application reaches a size where rendering the whole app at initial startup becomes unfeasible, you can start looking at conditional rendering at a higher level, such as only rendering the active page. If a single page is so big that it's unfeasible to render at once, then you probably have bigger problems.

**Comment by KeithHenry** [comment]
@ruphin That results in lots of `No property 'foo' on undefined` errors.

Do you mean:

```ts
return html`<div>${thing ? thing.foo : null}...${thing ? thing.bar : null}</div>`;
```

In which case my original question still applies, and it's a right pain to code when `thing` has a lot of properties.

Do we need an `if` directive?

**Comment by ruphin** [comment]
No, what I wrote was correct. The error you are seeing is caused by elements failing to initialize because their properties are not set. Something like this happens:

```javascript
return html`<div hidden?=${!user}>
  <my-user-panel user=${user}></my-user-panel>
  ...
</div>`;
```

Here `<my-user-panel>` is expecting `user` to exist during construction and is trying to access `user.name` or something similar, which throws that error you described. If you would use an if clause, `<my-user-panel>` would never be created with an undefined `user`, avoiding this error.

In general I consider it to be an anti-pattern when elements require certain properties to be present when they are initialised. In this case I think it is wrong of `<my-user-panel>` to always expect `user` to exist, and not having a default/fallback value. In your example, `thing` should have a fallback value of `{}` which will eliminate the need for these checks. For any template, it is _always_ possible to write it without any conditional `if` clauses, as long as you have properly set defaults or fallback values.

It's up to the developer to choose what style they want to use. Technically there is nothing wrong with conditional rendering using ternary ifs or some other mechanism, each comes with certain trade-offs.

I don't think this is lit-html 'issue', and this issue should probably be closed. For future reference, there is an active support channel on Slack at https://polymer.slack.com/messages/lit-html that is more suited for questions such as these :)

**Comment by KeithHenry** [comment]
Possibly, though this is likely to be a common problem that needs a documentation solution.

If the best practice pattern is to init all object properties with `{}` in the `constructor`, then we need to say that somewhere.

However, I'm not sure that is the case, as `<my-user-panel user=${user}></my-user-panel>` would still cause errors if the `user` variable is not set or set to `null`.

> In general I consider it to be an anti-pattern when elements require certain properties to be present when they are initialised.

Exactly! We should never assume that the property is set, at init or any future render.

Every time `_render` gets called in `<my-user-panel>` the `user` property may or may not have a value.

When it doesn't how _should_ that logic best return a reusable template with parts set by the sub-properties?

**Comment by justinfagnani** [comment]
I think @ruphin has given good answers here already, but to second those and summarize a bit:

1. It indeed doesn't much matter what you rendering the "empty" case
2. The new `when()` directive will cache the DOM nodes if you're switching a template on and off frequently
3. Setting `hidden` is often better, since you don't perform DOM mutations and don't trigger custom element reactions. Though if you want to free the memory from the nodes then a ternary is better.
