### ISSUE TITLE
[docs] Should shared styles be templates or strings?

### ISSUE THREAD

**Issue by KeithHenry** [Polymer/lit-html#396]
I have shared styles that move to being a constant with lit-html.

Should these shared constants be strings or templates?

```js
import sharedStyles from './shared-styles.js'
// export default const sharedStyles = html`<style>...</style>`;

const localStyles = html`${sharedStyles}
<style>
    :host { ... }
</style>`;

...
    return html`${localStyles}...`;
```

or 

```js
import sharedStyles from './shared-styles.js'
// export default const sharedStyles = '...';

const localStyles = `${sharedStyles}
    :host { ... }`;

...
    return html`<style>${localStyles}</style>...`;
```

Does it make a difference, give that no values change in these style constants?

**Comment by justinfagnani** [comment]
If no values change, it probably doesn't make that much difference, but we really need to measure these things better to know for sure.

The advantage for strings is that the processing is simpler due to skipping lit-html entirely.

The advantage for templates is that we create a real `<template>` element, and the browser might be able to cache and clone the resulting StyleSheet object, as well as reusing the backing string. But that might only kick in if there are no interpolations in the style text at all.

Another option that I think will align with future non-JS module types is to make shared styles an actual StyleSheet object. This might be a little too bleeding edge, but I'll be trying it out really soon. Shared styles keep coming up in questions and platform discussions.

**Comment by arthurevans** [comment]
Currently we don't talk about this much in lit-html. LitElement has its `css` and `unsafeCss` tags, which I think @justinfagnani was talking about moving into lit-html?

**Comment by justinfagnani** [comment]
I was thinking about that, especially to share the CssResult type so they could be used in templates. I'm not sure where we are with that decision.

**Comment by justinfagnani** [comment]
There are a few reasons not to move `css` as is into lit-html - it's currently too tied to how LitElement uses it. Closing this for now until we have some better ideas.
