### ISSUE TITLE
Running reference functions on render

### ISSUE THREAD

**Issue by aaronshaf** [Polymer/lit-html#424]
It'd be nice if

```
<hello-world ref={setRef}></hello-world>
```

... ran the `setRef` function with the first argument of the node.

#ReactRefugee

**Comment by ruphin** [comment]
You can sort of get what you want by using directives. Directive function have access to the part to which they apply, which have access to the node they are attached to. However, this is something you have to code up yourself. In most cases, there are much easier alternatives. 

In your example, you want to set a `ref` property that is the result of a function that has a reference to the node. You can solve it like this (leaving out all the irrelevant code):

```javascript
class HelloWorld extends HTMLElement {
  set ref(func) {
    this._ref = func(this);
  }
  get ref() {
    return this._ref;
  }
}

// Now you can do this
const setRef = (node) => { /* some code that uses node */ };
html`<hello-world .ref=${setRef}></hello-world>`
```

You can make things work exactly the way you want them to, but you have to do it yourself. This is the nice thing about Web Components. There are no 'if you put a function in a property reference that function is resolved with the node as the first argument' sort of things by default. The default behaviour is exactly what plain JavaScript does. If you want special behaviours like that, you can build them yourself.

**Comment by ruphin** [comment]
That would require a directive.

```javascript
const setRefDirective = directive(part => setRef(part.element));
html`<hello-world><input .ref=${setRefDirective} type="text"></hello-world>`
```

Something like that (the API is not finalised yet)

What do you want to do with this `setRef` function though? Do you just want a reference to the element? HTML has a native way to reference elements, with `id`:

```javascript
const template = html`<hello-world id="thing"></hello-world>`
render(this, template)
const ref = this.getElementById('thing')
```

Not sure if this is what you want, but it's just an example. Depending on what you want to do, there's probably a solution that doesn't require this reverse reference in the template.

Sometimes I see people trying to bring patterns from other frameworks over and trying to apply them here. Instead, figure out what it is that you actually want to achieve, and then find a way to do that, instead of trying to make the pattern work.

**Comment by justinfagnani** [comment]
lit-html 2.0 adds the `ref()` directive and the `createRef()` function, so we can do:

```ts
const buttonRef = createRef();

render(html`<button ${ref(buttonRef)}>Click Me</button>`, document.body);
const button = buttonRef.value;
```
