### ISSUE TITLE
Order of elements in Array is not followed (after initial render)

### ISSUE THREAD

**Issue by HoffmannP** [Polymer/lit-html#460]
If you change the order of HTML-elements (e.g. by a drag'n'drop script) corresponding to array-elements and rerender this array the old order is left in place.
[view on CodePen](https://codepen.io/anon/pen/MqbwEX)

(I assume the behaviour is intended but how can I force a hard redraw?)

**Comment by ruphin** [comment]
This is expected. You're not supposed to manually (or through script) manipulate rendered content. It will most likely break things, because especially when rendering Arrays, lit-html creates a special structure that it needs in order to re-render efficiently.

If you want to move elements, then change the order in the original array, and let `lit-html` render that array again. In most cases it will be nearly as efficient as switching DOM nodes around. If your elements are keyed (they have unique state), you can use the `repeat` directive to move elements around.

Think of lit-html as a "pure" function that maps a state to a certain DOM tree representation. If you want to change the DOM tree, then change the state, and let lit-html map the new state to the DOM tree.

**Comment by ernsheong** [comment]
I am seeing this as well. I want to implement Drag-n-Drop functionality. Most of the time it works but sometimes it does get wonky. What can we do about this?

**Comment by LarsDenBakker** [comment]
This is expected behavior. You can do what ruphin explained in his comment, change the data structure and let lit change the order.

**Comment by ernsheong** [comment]
Coming from LitElement, does it make sense to have an LitElement API to force re-render? I mean, for drag and drop there's really no way to cancel it after the fact, and instead of hacking a workaround (shifting elements back and updating model), just try to force a fresh render?

**Comment by ruphin** [comment]
The correct way to handle this is to have the drag-and-drop action change the datastructure in your element that describes the content (and it's order), and then re-render. You should always avoid manipulating elements manually.

**Comment by HoffmannP** [comment]
I wrote a minimal example for drag'n'drop in lit-html: hoffis-eck.de/exampleDnDLitHtml/

**Comment by aadamsx** [comment]
@HoffmannP, thanks for sharing your code!!  There's so little info/examples out there, sharing like this helps the community. :)

**Comment by ernsheong** [comment]
I have mastered the art of drag and drop within the same list, but dragging and droppping from one list to another using lit-html is a real usability issue and I am still struggling through it. (I am building a kanban board)

Maybe the thinkers around here have a better idea on how this can be easily accomplished, but so far it's been a real pain when the dragging and dropping goes across Shadow DOM component boundaries with their own list properties...

**Comment by justinfagnani** [comment]
@ernsheong I think there are two general ways to accomplish this:

- 1 You never mutate the DOM directly. The drag operation styles the element so that it follows the cursor with a CSS transform, but upon drop an event is fires to mutate the data, which then re-renders the DOM with the item in its new location as derived from the updated data.
-2 You preserve the dragged item by closely coordinating data and DOM updates via special directives. In this case you would keep the dragged item, but you have to tell one directive that it was removed and hand it off to another directive so that it knows it's there. This would essentially be a modified `repeat()` with an ability to adopt an item part and it's DOM. The `cache()` directive has some relevant code in it too.

cc'ing @rictic and @straversi who've both done some experiments in this area.

**Comment by straversi** [comment]
I agree with @ruphin and @justinfagnani. I did do a little bit of experimenting around animating the other items during a drag sequence: https://stackblitz.com/edit/lit-drag-n-drop

The next natural problem in my mind is: how to animate the _dropped_ item into place. If you mutate the underlying list immediately upon dropping, then lit will re-render, and there's not chance for 
a drop animation. One solution would be to mutate the list upon completion of a drop animation.

**Comment by bulletbrand** [comment]
> I wrote a minimal example for drag'n'drop in lit-html: [hoffis-eck.de/exampleDnDLitHtml](http://hoffis-eck.de/exampleDnDLitHtml/)

Hi man maybe you still have example of dragn drop code litElement, because your link dont work, but it would be very helpfull for me and other

**Comment by HoffmannP** [comment]
Here is the link to my repo: https://github.com/HoffmannP/exampleDnDLitHtml

**Comment by mercmobily** [comment]
@justinfagnani Would you be able to explain this a little further?

> -2 You preserve the dragged item by closely coordinating data and DOM updates via special directives. In this case you would keep the dragged item, but you have to tell one directive that it was removed and hand it off to another directive so that it knows it's there. This would essentially be a modified repeat() with an ability to adopt an item part and it's DOM. The cache() directive has some relevant code in it too.

We would like to move elements from one element (with its own data/render) to another element (with its own data/render).

We are finding that on dragend, the element we are dropping is *not* the element we have in the DOM.

Can you explain further what you wrote above? Just a little detail would do wonders. Thank you either way.

**Comment by justinfagnani** [comment]
@mercmobily what I'm describing is a bit of a complex operation that's similar to what the `cache()` directive does (it preserves detached DOM) but coordinated across multiple directives()/containers().

We've been thinking about these kind of helpers in terms of what we're calling "reactive controllers" recently - these are objects that can preserve state and utilize the component lifecycle across renders. There are equivalent techniques for raw lit-html, but it's easier to show with LitElement.

The idea is you'd have a helper that worked like `repeat()`, but it could detect moves across _multiple_ lists. If an item is moved between lists, its DOM is actually moved too. Also, in order to perform FLIP-style animations, it might need to measure all item DOM before anything is moved.

Using it would look like:

ts```
animatedListsController = new AnimatedListsController();

render() {
  return html`
    <ul id="list-1">
      ${this.animatedListsController.repeat(this.list1, (i) => html`<li>${i}</li>`)}
    </ul>
    <ul id="list-2">
      ${this.animatedListsController.repeat(this.list2, (i) => html`<li>${i}</li>`)}
    </ul>
  `;
}
```

This is definitely something we should at least prototype, since we need to show it working even if we don't ship production-ready helper just yet.

**Comment by mercmobily** [comment]
Oh I see. The idea -- correct me if I am wrong -- is that if two different elements could potentially share elements thanks to DnD (or anything else), they would use the same `animatedListController` variable to show the list, and `animatedListController` would be smart enough to make sure that DOM elements would be preserved -- right?

I can't even start to imagine what on earth animatedListController would need to do in order do actually perform such magic! But, yes, that would do the trick for us. And yes, it would be a much needed feature.
