### ISSUE TITLE
Application level blur handler called from render

### ISSUE THREAD

**Issue by annolangen** [Polymer/lit-html#495]
I am attempting a lit-html variant of the todomvc app (See todomvc.com for more info). While editing a todo item, ESC key is supposed to cancel the edit and clicking elsewhere (blur) is supposed to commit edited content. To my surprise, my blur handler was called from render while it was removing nodes as part of its update processing after pressing ESC. 

Adding a breakpoint in endEdit (model.js:63) shows the following trace:
endEdit (model.js:63)
save (controller.js:28)
html (controller.js:32)
handleEvent (parts.ts:422)
removeNodes (dom.ts:46)
clear (parts.ts:292)
_commitNode (parts.ts:195)
_commitTemplateResult (parts.ts:231)
commit (parts.ts:181)
_commitIterable (parts.ts:274)
commit (parts.ts:184)
update (template-instance.ts:50)
render (render.ts:44)
show (controller.js:41)
html (controller.js:37)
handleEvent (parts.ts:422)

I am attaching the mostly working app below. The relevant part for this bug is from controller.js. 

	const save = title => show(endEdit({id: editing, title}));
	const todoEdit = ({id, title}) => html`
	  <li class="editing">
			<input class='edit' autofocus value=${title} 
			  @blur=${({target}) => save(target.value)}
			  @keypress=${({target, keyCode}) => { if (keyCode === ENTER_KEY) save(target.value);}}
			  @keyup=${({target, keyCode}) => {
		if (keyCode === ESCAPE_KEY) {
			target.value = title;  // blur handler has been seen to fire in addition
			show(getItems());
		}
	}}>
		</li>`;
	render(html`${list.map(todo => editing === todo.id ? todoEdit(todo) : todoView(todo))}`,
			todoList);

The handler set with @blur= is called as part of the handler set with @keyup=. The ugly resetting of target.value to the previous title value is just there to mask the effect of the unexpected blur handler. I would like to be able to simply write 

   @keyup=${({keyCode}) => if (keyCode === ESCAPE_KEY) show(getItems())}

Detailed instructions to reproduce.  Observed in Opera 55.0.2994.44 and Chrome 68.0.3440.106
- Bring up attached app
- set break point in module.js:63
- create a todo
- double click to edit
- focus (the need for explicit focus is a separate problem. autofocus does not seem enough)
- press escape key

I am not expecting to hit the breakpoint. While I understand that the input element for editing need no longer be in the DOM tree when render returns, I am not expecting a blur callback. To my mind this is a leaky abstraction problem. I would like to remain unencumbered by the implementation of render when I reason about my application level event handlers.

[todomvc.zip](https://github.com/Polymer/lit-html/files/2377264/todomvc.zip)

**Comment by ruphin** [comment]
I'm fairly certain your issue is that you are rendering an `<input>` element in two different templates. Because they are different templates, lit-html will destroy the current input and render a new one, causing the `blur` event to fire on the input that is destroyed. Lit-html is not a diffing engine like virtualDOM, so it doesn't understand you are rendering the same input if you are not rendering the exact same template. If you want the same element to remain, you need to render the same template. 

More specifically, you need to merge `todoView` and `todoEdit` into a single template. You can use conditionals or nested templates to get the same end result.

**Comment by ruphin** [comment]
Yes.

Consider your question in a scenario where your render implementation was nothing but calling `innerHTML`. Obviously you have to consider how you render things, because it affects how the DOM behaves, and how/when it fires events.

If you attach event listeners to nodes that fire when nodes are removed, and you instruct your render engine to remove the nodes, they will fire the events and call your handlers.

When you give lit-html a new (different) template to render, it will destroy all existing nodes, and render the new template. If you want the nodes to be re-used, you have to render the same template. That's how it works.

**Comment by justinfagnani** [comment]
Thanks for answering this @ruphin 

I've seen the root problem here (rendering different templates and expecting diffing-type behavior) come up a few times recently. We definitely need to highlight this in the docs.
