### ISSUE TITLE
Export directives as top-level package exports

### ISSUE THREAD

**Issue by kuka-radovan** [Polymer/lit-html#508]
Is there any reason, why directives are not top-level package exports? Also tslint [complains](https://palantir.github.io/tslint/rules/no-submodule-imports/) that submodules are treated as internal API and best practise is to stick only with top-level exports.

If there is no specific reason about that, I can submit PR to fix that.

**Comment by mkay581** [comment]
Yeah, at the very least, all directives should be importable from the same file (ie directives/index.js).

**Comment by justinfagnani** [comment]
Since we don't know what directives might be used, we don't want to export them all and force all their implementation code to be loaded. Directives are going to stay in their own modules so they can be imported a la carte.

I would suggest that the tslint `no-submodule-imports` rule is rather presumptive and definitely won't apply generally. lodash-es, for instance, publishes submodules and they are definitely prefered over the main module.
