### ISSUE TITLE
Template syntax checking

### ISSUE THREAD

**Issue by zeroliu** [Polymer/lit-html#519]
Currently, no error is thrown when template contains invalid DOM elements. The incorrect template string is ignored by innerHTML and can be difficult to debug. For example:
```
<div class="foo></div>
```
It results in an empty template because of missing closing quote.

I find even a generic 'invalid template' error message would be very helpful. It can be done during the template creation phase. It is also a good step to have if we add template pre-processing support.

**Comment by ruphin** [comment]
Lit-html does not process templates, everything is done by the browser. Because browsers don't throw errors when they process invalid HTML, there is no way for lit-html to know if the templates were valid, other than by embedding an HTML parser, which defeats the entire purpose of what it is trying to do.

I think this problem is out of scope. The right place to solve this is with tooling like linters or other pre-processing tools that can warn the developer about incorrect HTML.
