### ISSUE TITLE
explicit call to commit after part.setValue in directive

### ISSUE THREAD

**Issue by arfost** [Polymer/lit-html#534]
Hi,

I'm currently trying lit-element/lit-html with firebase on a pet project.
I made a firebase directive, to automatically update content when a new data event fire.

Here is the directive 

```javascript
    //ref is a firebase reference, content and defaultContent lit-html template
    const onFirebaseData = (ref, content, defaultContent) => directive(part => {
        part.setValue(defaultContent);
        ref.on("value", snap => {
            let data = snap.val();
            if (data !== undefined) {
                part.setValue(content(data))
            }
        })
    });
```
After being busy for about one month, I came back to the project, upgraded to latest versions, and the directive stopped working.

After looking in the code, I managed to get it do it's job again by adding 
`part.commit()` after the `part.setValue()`

new version 
```javascript
    //ref is a firebase reference, content and defaultContent lit-html template
    const onFirebaseData = (ref, content, defaultContent) => directive(part => {
        part.setValue(defaultContent);
        ref.on("value", snap => {
            let data = snap.val();
            if (data !== undefined) {
                part.setValue(content(data))
                part.commit()
            }
        })
    });
```

It seems strange to me to add this call for the same behavior and I don't see any advantages in this, so I'm not sure if I'm missing something, and using it wrong.
There is also no mention I could found in the documentation
[directives](https://polymer.github.io/lit-html/guide/writing-templates.html#directives)
of this call to commit.

Can someone explain me what is going on here ?

Thanks in advance.

**Comment by justinfagnani** [comment]
Yeah, I need to update the docs (cc @arthurevans ), but what's going on here is that there are two phases to updating DOM: the setValue phase, and the commit phase. DOM is only mutated in the commit phase. This split exists so that we don't update attributes or properties multiple times if they have multiple bindings.

Directives are invoked during the commit phase, but you can call `setValue()` in a directive and the new value will still be committed. However if you call `setValue` at a later time, when not already in a commit, such as in the event callback you have, you need to manually call `commit`, or the new value just sites there.

**Comment by kevinpschaaf** [comment]
I believe the docs now cover when `commit` is required over just `setValue`: https://lit-html.polymer-project.org/guide/creating-directives#asynchronous-directives.

Closing as resolved.
