### ISSUE TITLE
lit-html, lit-element and redux : _stateChanged ignore template attributes update

### ISSUE THREAD

**Issue by vdegenne** [Polymer/lit-html#545]
Also I came to this specific use-case where a `LitElement` updates one of its attributes from a redux state property and an attribute in a `lit-html` template (the template returned from the `render` method).

Here's the [reproduction](https://glitch.com/edit/#!/redux-lit-html-states-and-attributes)

I tried to simplify as much as I could.
Simply put, the main view (`person-view`) html is embedding another custom element (`person-card`) and set one of its attributes using the "dot notation" (`.personId="${this._personId}"`).
When the state changes (clicking the button) the main view updates its property `_personId`. Naturally I was expecting the view to update the html attribute of `person-card` as well so when `person-card` `_stateChanged` method is called its property `personId` value is coherent to the application global state.
I found that was natural because `person-card` is one leaf of the tree which is the application and should rely on its parents' state.

I think this behavior is caused from the methods `_stateChanged` called in an asynchronous way or technically not awaiting upper elements dom full update (I can't really tell as my understand of how the core libraries work is limited).

As for now I am trying to find a workaround but If you think this case deserves special attention I'd be gladly waiting for an update.

Love you Polymer Team !

**Comment by vdegenne** [comment]
Just a quick addition, this is the [workaround](https://glitch.com/edit/#!/redux-lit-html-states-and-attributes-workaround) I found and I think this is the syntax some `lit-element` showcases are using.

However in my project I really need to do the treatment in the `_stateChanged` method because the computed property is coherent to the element and is used subsequently in other elements' methods.
What I mean is that the property is not used for rendering purpose only. So I maintain the state of this issue.

**Comment by bgotink** [comment]
It looks like `lit-element` will rerender the template of the view asynchronously, so it turns out the `personId` gets updated in the child component _after_ the `_stateChanged` method has been called. In your example the parent already has the correct state, but this state hasn't been propagated to the child yet.

I'm not sure what the best approach is to solve the issue (add a synchronous variant of `_invalidate` to `LitElement`?), but in any case this looks more like an issue for [Polymer/lit-element](https://github.com/Polymer/lit-element) than lit-html. Could you open a ticket there?

**Comment by vdegenne** [comment]
@bgotink Ok I will, thanks for your answer.
