### ISSUE TITLE
Related projects: icomponent

### ISSUE THREAD

**Issue by prasannavl** [Polymer/lit-html#617]
Hey folks! First of, thanks for lit-html. It's a fantastic project that aims to simplify the rabbit hole that is web frameworks. 

I've just published `icomponent` (https://github.com/prasannavl/icomponent): a super simple  component library that emphasizes framework and renderer freedom, which is largely made possible due to `lit-html`, and the likes. 

Most of the examples I've written in the README are `lit-html` examples. I was wondering if guys would be kind enough to add a small "Projects using lit-html", or "Related projects" section to the README where projects like `icomponent` can be given a small hand wave.

Cheers! Thanks.

**Comment by ruphin** [comment]
Thanks for choosing `lit-html` for your component library. It is great that there are many projects around that use lit, but listing them all is probably outside the scope of this repository.

There is a community managed repository that lists projects that use lit-html or are related:
https://github.com/web-padawan/awesome-lit-html/

It accepts pull requests, so you can make a PR to get your project listed there. :)

**Comment by justinfagnani** [comment]
I think @ruphin's suggestion is good for now.

We may want to include a section on the docs eventually, especially because we will want to feature links to LitElement for using lit-html with Web Components, but at the same time I don't want to overly preference our own related projects at the expense of others (@ruphin's Gluon library included :) ). We'll probably have to figure out some criterion for being listed if we do that.

I'm going to close this for now, but will keep you in mind when we get to this part of the docs.

**Comment by prasannavl** [comment]
Sounds good! Thanks @ruphin and @justinfagnani :)
