### ISSUE TITLE
lit-html swallowing siblings to custom components with svg

### ISSUE THREAD

**Issue by prasannavl** [Polymer/lit-html#623]
Okay, it seems lit-html is swallowing components in specific cases: I haven't yet nailed down exactly when this, but I suspect it has to do with `svg` tags, and here's a simple full example where I noticed it.

I also tested this by swapping out `lit-html` by `hyperhtml` where it seems to work perfectly as expected.

In the following example, anything that follows the custom component `custom-svg` is "swallowed" by `lit-html` - not rendered into the DOM.

```js
// html is just reexported from lit-html.
import { IComponent, defineTag, html } from "icomponent-lit/lib";
// swap comments and everything works as expected
// import { IComponent, defineTag, html } from "icomponent-hyper/lib";

class App extends IComponent {
  view() {
    console.log("render");
    return html`
      <div>Hello</div>
      // removing this renders the next div. 
      <custom-svg/>
       // This following tags are swallowed unless the above is commented out.
      <div>Goodbye!</div>
    `;
  }
}

console.log("defining");
defineTag("x-app", App);

defineTag("custom-svg", () => {
  return html`
    <svg viewBox="0 0 512 512"><path fill="#000" /></svg>
  `;
});

// html: <x-app/>

**Comment by cyper8** [comment]
self-closing tags as `<custom-svg/>` aren't supported by `CustomElements` specification: [Issue](https://github.com/w3c/webcomponents/issues/624).

Change it to `<custom-svg></custom-svg>` and it is gonnabe all right.

And there is a `svg` tag function in `lit-html` library, too.

**Comment by prasannavl** [comment]
@cyper8, thanks! That seems to do it. 

(wondering though, if I should leave this open for now, until it makes it way to the docs, or if this behavior can be handled inside lit-html itself -- where hyperhtml for instance, works seamlessly)

**Comment by ruphin** [comment]
This is not a lit-html issue. 

I don't know what makes it "work" with HyperHTML, but the behaviour from lit-html is correct according to the specs. The Custom Elements specification does not allow self-closing tags with Custom Elements. Any content that follows your element tag before the appropriate closing tag is placed into the subtree under the Custom Element, which causes them to be hidden, because the Custom Element renders the shadow tree instead.

See this example that does not use lit-html:
https://codepen.io/ruphin/pen/bQgLqP?editors=1010
