### ISSUE TITLE
`repeat` not reusing dom correctly

### ISSUE THREAD

**Issue by prasannavl** [Polymer/lit-html#629]
I've been trying to do replicate a react-transition-group like effect, with `until`, and `repeat`. Below is semi-code for the same. But the problem I'm having is, it looks like it's lit-html is not correctly reusing the dom, even through my message ids are correctly generated. I'm unsure if I'm using the directives in an incorrect way, or if it's a bug.

```js
  view() {
    let messages = this.store.messages;

    let msgView = function (x) {
      return until(
        delay(1000)
        .then(() => 
      html`<div class="text-column show">${x}</div>`),
      html`<div class="text-column">${x}</div>`
      );
    }

    return html`
        <div class="text-columns">
         ${repeat(messages, x => x.id, x => html`${msgView(x.value)}` )}
        </div>
      `;
  }
```

PS: Off topic, this also makes me wonder, does `lit-html` hold on to a promise forever until it resolves or rejects? What's the correct way to ask nicely for `lit-html` to stop tracking a promise.

**Comment by mariusGundersen** [comment]
Can you clarify what you mean by "it looks like it's lit-html is not correctly reusing the dom"? What do you expect to happen and what happens instead? 

The `repeat` directive will hold on to the DOM of each item, but it will *update* the item when it rerenders. In your example above that means that `msgView()` will be called for each item in `messages` each time `view()` is called. Since `msgView()` is called again, it will create a new promise (I guess that is what `delay(1000)` does?). 

If you don't want it to *update* a part then you can use the `guard` directive to only update it when a parameter changes. So, if you don't want to rerender `msgView` every time, only when the parameter is changed, then you can do something like:

```js
    return html`
        <div class="text-columns">
         ${repeat(messages, x => x.id, x => html`${guard(x.value, () => msgView(x.value))}` )}
        </div>
      `;
```

**Comment by prasannavl** [comment]
@mariusGundersen

> Can you clarify what you mean by "it looks like it's lit-html is not correctly reusing the dom"? What do you expect to happen and what happens instead?

I expected that `lit-html` would calculate the diff and update only the class names of the existing dom node but I'm getting new nodes instead. I attached a `MutationObserver` to it's parent, and it clearly states nodes are being added and removed.

> Since msgView() is called again, it will create a new promise (I guess that is what delay(1000) does?).

Yeah, delay is just a wrapper around setTimeout as a promise.

> If you don't want it to update a part then you can use the guard directive to only update it when a parameter changes.

Yes, that's what I ended up doing, which seems to work. But my confusion is that, from the docs it  seemed like it was supposed to have similar behavior to say, react's `key`s, where it only touches the changed part. 

I also get these errors while doing it, sporadically:
```
Uncaught (in promise) TypeError: Cannot read property 'nextSibling' of null
    at removeNodes (dom.ts:46)
    at NodePart.clear (parts.ts:313)
    at NodePart._commitNode (parts.ts:215)
    at NodePart._commitTemplateResult (parts.ts:249)
    at NodePart.commit (parts.ts:194)
    at value.then.v (parts.ts:307)
```

**Comment by mariusGundersen** [comment]
Ok, many things to discuss here, lets start at the top.

> I expected that lit-html would calculate the diff and update only the class names of the existing dom node but I'm getting new nodes instead. I attached a MutationObserver to it's parent, and it clearly states nodes are being added and removed.

The repeat directive reuses existing DOM nodes, but it also updates that DOM node. That is, in a template with parts (each `${}` is a part) it will reuse all the static stuff, but it will recalculate the parts. So, lets say you do something simple, like this:

```js
${repeat(messages, x => x.id, x => html`<span>static only</span>`)}
```

Here each item that is repeated contains only static content (there are no `${}` in the template tag), and so everything can be reused. 

But if you have some dynamic part in it, for example:

```js
${repeat(messages, x => x.id, x => html`<span>${x.value}</span>`)}
```

Then it will reuse the static stuff (the `<span>` element) but it will update the text content with the value of x. But, lit-html will see that the new value of the textContent is the same as the old value and so it will not do anything to the DOM. So it will attempt to update the part but wont do anything to the DOM which means the update will return very quickly without any effect.

In your case you call a function inside the ${}, and you don't wrap it in a `<span>`. This means that the result of the function is inserted directly into the parent of the list, which is why you see changes in the `MutationObserver`. If your function returned just static content, then it wouldn't need to change anything, but you are working with a promise.

> But my confusion is that, from the docs it seemed like it was supposed to have similar behavior to say, react's keys, where it only touches the changed part.

Yes, the problem here is that the `msgView` function isn't stateful, there is no way for it to update without starting over from scratch. In react there is a difference between creating a component and updating a component, but that's not as easy in lit-html. I have a [proposal](https://github.com/Polymer/lit-html/pull/591) for how that can be possible in lit-html. This proposal would also mean that you could write ``${repeat(messages, x => x.id, x => msgView(x.value))}`` instead of ``${repeat(messages, x => x.id, x => html`${msgView(x.value)}` )}``. 

> I also get these errors sporadically, with the above code (not sure if it's related yet)
> how do ask "nicely" inorder for lit-html to stop tracking a promise

Unfortunately there isn't any way to cancel a promise in JavaScript, the only option is to ignore the value the promise resolves to. lit-html will handle this correctly if the value of a part is changed directly, for example:

```js
const app = (ms, value) => html`<span>${delay(ms).then(() => value)}</span>`;
render(app(100, 'one'), elm);
render(app(1000, 'two'), elm);
```

This will work correctly because the promise is switched out directly. But lit-html doesn't know when a subtree is removed from the page, only when a direct descendant is removed, so this example will cause the error you see:

```js
const app = (show, ms, value) => html`<span>${ show ? html`${delay(ms).then(() => value)}` : 'hide'}</span>`;
render(app(true, 100, 'one'), elm);
render(app(false, 100), elm);
```

#591 fixes this too.

**Comment by prasannavl** [comment]
@mariusGundersen Thank you so much for the detailed explanation! I appreciate you taking the time to explain the rationale in detail. This is of immense help. :) 

I'm keen to track the progress of #591.
