### ISSUE TITLE
Self closing tags

### ISSUE THREAD

**Issue by kaaninel** [Polymer/lit-html#630]
As far as i can see we can't use self closing tags (<custom-element />) in HTML5. I tried using XHTML instead but that have problems with <script type="module"> so i was wondering is there any way we can do this while processing template inside html template literal ? I heard hyperHTML already doing this as you can see at [hyperHTML referance](https://github.com/WebReflection/hyperHTML/blob/7509fcac074217fbc1bcd01d72b0cbd2a122d7fe/cjs/hyper/render.js#L65) .

**Comment by web-padawan** [comment]
Custom Elements can not be self-closing per spec. See w3c/webcomponents#624

**Comment by ruphin** [comment]
Self-closing tags are not allowed for Custom Elements, because they are not allowed in HTML5 in general, outside [foreign elements](https://www.w3.org/TR/html5/syntax.html#foreign-elements). Regular HTML elements allow the self-closing solidus [_only_ on void elements](https://www.w3.org/TR/html5/syntax.html#start-tags), on which they are optional and have no effect.

Lit-html uses the native template parser in browsers, so it will allow whatever syntax is allowed by the HTML5 specification (assuming the browsers implement correctly). The main advantage of this strategy is that we do not have to implement a parser, because we use the available builtin parsers. It is unlikely that we will want to deviate from this strategy to add support for features like self-closing tags that are not part of the HTML5 spec.

**Comment by justinfagnani** [comment]
There are ways to do regex replacements on the template strings to support self-closing tags, but I don't think it's really worth the code or extra scans.

I'll leave this issue open to see if there's a lot of demand though.

**Comment by kaaninel** [comment]
Maybe we can create a config system for this kinda features ? I don't like bloated libraries too. But I think lit-html should be a solution for runtime problems. At future maybe there can be a typescript plugin(transformer) does this kinda compile time problems too which honestly i would prefer that and working about it. But since that time we need at least a temporary solution for this kinda problems i think. I'm developing a custom element library just like lit-element so i created symlink from lit-html's src folder to my lib folder now tsc compiles lit-html inside my project and i can implement some changes that i need so this is not really a problem for me currently. I think more people should prefer lit instead of solutions like react or vue but people who are used to jsx nags about this kinda small syntax problems constantly whenever i show to them. I tried not using a full regex search and some small string processing but im pretty sure somebody can write a better implementation that is good enough people would prefer losing that speed for this feature.

**Comment by jsilvermist** [comment]
IMO I don't like the idea of supporting self-closing tags because that's not really a thing in HTML5, mostly it's just either void elements or normal elements. Adding more processing just to solve something that isn't standard and that any decent IDE/Text Editor will autocomplete anyways seems like a waste to me.

**Comment by stramel** [comment]
Having worked with Polymer since v1 and with React, I can say personally that the main thing that I found as a nice to have from the React/JSX self closing tag is the neatness of the code. I often found the autocomplete of an editor more than enough to handle the "burden" of a closing tag.

With that said, I don't see why someone couldn't write a basic compile plug-in to handle a self closing tag to what the DOM would expect. This would allow a user to opt-in knowing the pros and cons of it without affecting the runtime.

**Comment by jsilvermist** [comment]
@stramel The downside to that approach is that either the element creator has to precompile their element before publishing, or expect the end user of the elements to add the plugin even if they don't want to use self closing tags themselves.

**Comment by justinfagnani** [comment]
When needing to make a choice, we're going to optimize for familiarity to HTML over JSX. HTML doesn't support self-closing tags, so the impetus here is much less.

I'll point out that this can be pretty easily done with a custom TemplateResult class - so one should be able make their own fairly trivial subclass of TemplateResult that overrides `getHTML()` and runs the regex/replace that expands self-closing tags.

**Comment by hyperpress** [comment]
Good discussion. The key here, to me, is does a change comply with or run
counter to, in this case, the HTML5 specification? I understand a lot of
developers are used to and like self-closing tags, it seems like a change
that is either unnecessary or adds complexity beyond the scope of the
intended library. Maybe this would be a good tooling project, but I'm
hesitant to advocate for this type of change in lit-html itself.

**Comment by stramel** [comment]
Just saw this, `htm` by @developit https://github.com/developit/htm

Interesting that he is supporting self-closing tags in his library.

**Comment by kaaninel** [comment]
[EmpatiElement/Template:EmpatiTemplate.getHTML()](https://github.com/EmpatiLab/EmpatiElement/blob/89141c289b49d49190c35babbf6dc81bd4630854/Client/Source/Template.ts#L8) if anybody needs that's how im using it.

**Comment by blikblum** [comment]
Ive just got bitten by this.

While converting a project from JSX to lit-html / lit-element i kept the self closing tag as in JSX:

```javascript
const obj = {value: "great"}
return html`<my-element .mood=${obj}/>`;
```
At first look worked. The element is instantiated and upgraded but the object property being passed to it was converted to '[object Object]'

Debugging i found that the part was converting the value to string because part.single was false

Finally the culprit was that i was not using quotes around the property value as suggested [here](https://github.com/Polymer/lit-element/issues/363#issuecomment-449097371)

Those variations worked:

```javascript
return html`<my-element .mood="${obj}"/>`;
return html`<my-element .mood=${obj}></my-element>`;
```

Here's the complete example
https://codepen.io/blikblum/pen/dwjvyX?editors=1000

I think the not support for self closing tag for web components should be well documented, since IMO will be a common situation

**Comment by LarsDenBakker** [comment]
It is well documented in the HTML spec :)

**Comment by blikblum** [comment]
Average programmers do not read specs, many are not even aware of its existence, so documenting somewhere will save a bunch of issues when/if lit-html becomes popular among them. And don't expect detailed issue with sample code, already debugged like i did. Is just: "does not work"

Anyway, this issue is particularly catchy because, apparently, works with quotes or using string properties. Than add an object property and suddenly does not work

**Comment by justinfagnani** [comment]
There could be a place in the docs for this under Template Structure: https://lit-html.polymer-project.org/guide/template-reference#template-structure

cc @arthurevans

**Comment by adrm** [comment]
Hi, I understand and support the logic behind not supporting self-closing tags, but it is confusing coming from JSX. A heads-up in the documentation would be good enough.

**Comment by justinfagnani** [comment]
This is not planned.

**Comment by angryziber** [comment]
Here a way to implement this on top of `lit-html`, if anybody is looking for:
```
function htmlWithSelfClosingTags(strings, ...values) {
  let tagName
  strings = strings.map(part => {
    const hasEnd = part.indexOf('/>') >= 0
    if (tagName && hasEnd)
      part = part.replace(/^([^<]*?)\/>/, '$1></' + tagName + '>')
    if (!tagName || hasEnd)
      tagName = part.match(/<([^ >]+)[^>]*?$/)?.[1]
    return part
  })
  return html(strings, ...values)
}
```

I just export this as `html` and use it instead of lit-html's function.

**Comment by aigan** [comment]
Ok. So I just started migrating to Lit 2. Didn't find an implementation of self-closing tags, so I ended up doing it. It's mostly a copy of the existing parser.

https://github.com/aigan/lit-self-closing

**Comment by DemiusAcademius** [comment]
Angular 15.1 just added self-closing tags

**Comment by justinfagnani** [comment]
@DemiusAcademius Angular has a custom HTML parser and compiles templates at build time. We do neither of those things and hand off the HTML string to the browser, which doesn't support self-closing tags.

**Comment by DemiusAcademius** [comment]
Do you have any plans for compile templates at build time in the future?
Thanks for answer

**Comment by seelts** [comment]
i can not agree with the "specification" reasoning

the whole purpose for Lit to exist, is to be a more convenient abstraction on top of that specification.  
otherwise why would one use it?

everyone understand self-closing tags and use them in other frameworks.  
i believe if Lit wants to gain at least some popularity, that (and not only that) feature should definitely be implemented.

and in case of "specification"... maybe let's get rid of everything that is not in there?  
for consistency.  
what about `<button @click="${() => this.active = !this.active}">Toggle active</button>` and alike... ?
