### ISSUE TITLE
Typed bindings are incompatible with XHTML

### ISSUE THREAD

**Issue by drivron** [Polymer/lit-html#634]
The following examples from the guide will fail on a XHTML document because the first characters of the attributes are not allowed in XML. `?` and `@` are not allowed at all, `.` is not allowed as first character.
```
html`<input type="checkbox" ?checked="${checked}" />`
html`<input .value="${value}" />`
html`<button @click="${(e) => console.log('clicked')}">Click Me</button>`
```

An alternative syntax like this one could be accepted by lit-html:
```
html`<input type="checkbox" b.checked="${checked}" />`
html`<input p.value="${value}" />`
html`<button e.click="${(e) => console.log('clicked')}">Click Me</button>`
```

**Comment by KeithHenry** [comment]
lit-html is designed to work with HTML5, it would require quite a few changes to work with XHTML (which is deprecated, so probably shouldn't be the target for a new framework).

In particular boolean attributes are not valid XHTML: Lit outputs `<input type="checkbox" checked />`, but XHTML needs `<input type="checkbox" checked="checked"></input>`.

You need different outputs, too.

**Comment by web-padawan** [comment]
Note that event and property bindings, like `@click` and `.value` are parts of syntax and do not end up in the actual markup produced by lit-html.

**Comment by rivron** [comment]
@KeithHenry
 - The XML syntax is part of the HTML 5 specification and the HTML Living Standard which do not specify it as deprecated.
 - I have not found any clue that lit-html will not support the XML syntax.
 - A boolean attribute is only the presence or absence of the attribute. HTML provides an syntaxic sugar for it, but both syntaxes accept this code `<input type="checkbox" checked="" />`.

@web-padawan
The template string with decorated attributes are assigned to the template content which inherits the host document type and parser (template-result.ts:72). The parsing fails at this stage.

**Comment by KeithHenry** [comment]
@rivron it isn't - XML is stricter than HTML and changes some rules. XHTML was an attempt to unify them that didn't really take off. XHTML was the hot newness over a decade ago, but _still_ doesn't have consistent browser support. I _really_ wouldn't recommend using it in new projects.

XHTML is a parallel branch to HTML5, neither is a subset of the other. However, as HTML5 is more forgiving it can mostly parse XHTML content just fine if you change the doctype.

lit-html's template syntax doesn't end up in the output HTML, so `.property`, `?boolean` and `@event` are never in the output. However, the whole point of `?boolean` is to create boolean attributes - a feature of SGML and HTML that isn't in XML or XHTML.

So, in SGML and HTML you can have an attribute without a value, like `<input checked>` - HTML5 sees this as a boolean property where `checked` is true if present or false otherwise. XML and XHTML don't, and require every attribute to have a value, so `<input checked="checked" />`. Unfortunately (and this is one of the reasons we all stopped using XHTML) `<input checked="false" />` is still seen as `checked == true`, because the value is parsed as a truthy string.

I think you can work around this with the `ifDefinied` `directive`, something like: 

    html`<input checked=${ifDefined(...)} />`. 

That should result in XHTML syntax compliant output, but I'm still not sure lit-html can work with it. You may be better off with either a JSX alternative (as you can explicty create each element in the right NS) or forking this to build something XHTML specific.

**Comment by rivron** [comment]
@KeithHenry
I didn't want to start a "HTML vs XHTML" debate here, this is why I have speak of XML syntax in my answer, which is part of the current specifications :
 - https://www.w3.org/TR/html52/xhtml.html#xhtml
 - https://html.spec.whatwg.org/multipage/xhtml.html#the-xhtml-syntax

Boolean attributes are a DOM concern, not a syntaxic one :
 - https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes
 - https://github.com/Polymer/lit-html/blob/master/src/lib/parts.ts#L358

**Comment by rivron** [comment]
This is the first feature of lit-html that breaks the compatibility with the XML syntax. Was it intentional ? Should we expect other features incompatible with it ?

P.S.: We have (easily) implemented acustom TemplateProcessor to handle a XML compatible syntax.

**Comment by KeithHenry** [comment]
@rivron I'm not arguing the versus, but the syntax _does_ matter: `<my-tag />` is valid XHTML but will fail in `<template>` (the HTML5 feature lit relies on, see #630). `<input checked>` is optimal HTML5 (so what lit users will expect) but invalid XHTML.

> We have (easily) implemented a custom TemplateProcessor to handle a XML compatible syntax.

The messy bit is supporting both at the same time. I think the syntax differences mean you either need `lit-xml` as its own fork, or possibly an `xml` template function (similar to what we already have for `svg`).

**Comment by justinfagnani** [comment]
XHTML is not something we're explicitly targeting right now, but I want to point out that support can be added with custom a `html` tag that uses a TemplateResult that overrides `getTemplateElement()` to use a separate HTML document created with `DOMImplementation.createHTMLDocument()`.

**Comment by justinfagnani** [comment]
I think XML support is out of scope for lit-html at this point. HTML and SVG are the main targets.
