### ISSUE TITLE
ShadyRender sometimes does not apply customization

### ISSUE THREAD

**Issue by csvn** [Polymer/lit-html#655]
### Description
For browsers using the `@webcomponents/webcomponentsjs` suite of polyfills, sometimes styling child elements via CSS custom properties are not applied. E.g. `my-component { --color: red }` CSS is not always applied to the `my-component` element.

As a workaround, it works if `ShadyCSS.styleElement(element)`/`ShadyCSS.styleSubtree(element)` is used to manually fix it. The drawback with this is it's hard to know when this works or not. Some places in our code the swatch works when resized, others not.

#### Native custom properties (e.g. latest Chrome, latest Firefox, latest Safari)
![image](https://user-images.githubusercontent.com/8770194/48919220-c6561900-ee91-11e8-9a23-f7a3ba311337.png)

#### Non-native custom properties (e.g. IE11, Edge 15, Safari 9.1)
![image](https://user-images.githubusercontent.com/8770194/48919152-7414f800-ee91-11e8-8998-eea86cdfa80e.png)

### Reproduction
https://stackblitz.com/edit/typescript-88yd5d

### Aside
Is there any documentation describing the limitations of ShadyCSS somewhere? I've seen that dynamic bindings are not supported (#265, #435), but are there other things to think about? If there are edge-cases or situations where manual works is required when using `shady-render.ts`, I'd love to know.

**Comment by csvn** [comment]
Let me know if something is unclear about the reproduction, and I'll update! 😄

**Comment by csvn** [comment]
I also had an earlier reproduction, but I could not get the error to manifest there. [In this example](https://stackblitz.com/edit/typescript-kxaoz6), theming via CSS variables works fine. Not sure why it works sometimes but not always.

**Comment by justinfagnani** [comment]
cc @sorvell and @azakus for ShadyCSS and @arthurevans for docs on ShadyCSS limitations.

**Comment by sorvell** [comment]
It is definitely a little tricky to use `shady-render` correctly.

Here is the original example modified to work: https://stackblitz.com/edit/typescript-dhbyav?file=basic-element.ts. Two changes have been made: 
  1. rendering is performed asynchronously at microtask timing rather than synchronously, 
  1. `ShadyCSS.styleElement(this)` is called in `connectedCallback` to handle moving between containers.

Let me explain why these changes are needed and then describe a couple library changes I think we could make to improve clarity.

In order for shimmed custom properties to work correctly, the following requirements must be met: 
  1. elements must be in the DOM tree when they try to shim custom properties (`ShadyCSS.styleElement` is called), and 
  1. any elements higher in the tree must already have shimmed custom properties (shimming must go in tree order).

This is [somewhat documented](https://github.com/webcomponents/shadycss#usage) in the ShadyCSS Readme.

In order to make `shady-render` easier to use, it automatically calls `ShadyCSS.styleElement` on first render. If the above conditions are met, then this works great. When they are not met, however, we've hidden the requirement that `ShadyCSS.styleElement` needs to be called. 

The simplest way to ensure that basic rendering works and the above conditions are met is to:
  1. Perform first render when an element is connected. This way it's in the DOM tree.
  1. Render asynchronously, at microtask timing. This way shimming goes in tree order since a host is rendered and calls `ShadyCSS.styleElement` (shady-render does this automatically) before any client which renders asynchronously. This was the first change made to the example.

Also, whenever an element moves and is connected, `ShadyCSS.styleElement` should be called so that properties are updated for the element's new location. This was the second change made to the example, and this means that element authors **should** always call `ShadyCSS.styleElement(this)` in `connectedCallback`.

To make this more clear, we could:
  1. Remove `styleElement` from `shady-render` entirely to make it more obvious that it should be called in `connectedCallback`.
  1. Change ShadyCSS so that calling `styleElement` attempts to ready a host element if it has not yet been shimmed. This should make the ordering requirement less tricky and avoid the need to render asynchronously.

**Comment by sorvell** [comment]
Using `lit-html 0.14.0` and `ShadyCSS 1.7.0`, this issue should be resolved.

It is still required that a custom element not render before `connectedCallback` and it should also call `ShadyCSS.styleSubtree(this)` in `connectedCallback` to ensure that when the element is moved, its styling is updated.

**Comment by csvn** [comment]
@sorvell Thanks a lot for the fix and information!

> any elements higher in the tree must already have shimmed custom properties (shimming must go in tree order).

I'll try updating versions, since this is most likely the reason why our styling broke. We render synchronously in our `connectedCallback` since it felt easiest for developers (e.g. quering elements). In all other cases, rendering is performed next microtask (e.g. re-render).

```js
class Foo extends CustomLitElement {
  connectedCallback() {
    super.connectedCallback();
    this.shadowRoot.querySelector('.bar'); // null if render is performed next microtask
  }
}
```

We use `ShadyCSS` in only two places in our code; `ShadyCSS.styleDocument()` to set some global custom properties, and `ShadyCSS.styleElement(this)` to fix a similar issue as the repro in this issue each render. The latter can probably be removed to add `ShadyCSS.styleSubtree(this)` to the connectedCallback in the base class.

- https://github.com/Polymer/lit-html/issues/655#issuecomment-442648651 mentioned that `ShadyCSS.styleElement(this)` should always be used, but I take it the latter comment suggesting `ShadyCSS.styleSubtree(this)` is the correct way?
- When there are no styling changes, is `ShadyCSS.styleSubtree(this)` operation heavy performance wise? I have not noticed that it is required for our code yet, and for IE11 it might make sense to sacrifice correctness for performance, as long as we know styling might be affected if an element is moved.

**Comment by arthurevans** [comment]
@csvn Update: talked offline, and confirmed you should use `styleElement` in `connectedCallback`, _not_ `styleSubtree`.
