### ISSUE TITLE
Feature request: allow setting boolean event listener options directly on the attribute name

### ISSUE THREAD

**Issue by b-strauss** [Polymer/lit-html#662]
Allow setting boolean event listener options directly on the attribute name.

The presence of the option would indicate the boolean `true` value.

This has been proposed in https://github.com/Polymer/lit-html/issues/145#issuecomment-400571460.

Strawman syntax (with support for multiple options):

```js
html`<div @scroll.passive=${this.onScroll}></div>`;
html`<div @click.once=${this.onClick}></div>`;
html`<div @click.once.capture=${this.onClick}></div>`;
```

**Comment by justinfagnani** [comment]
I think the cons listed in that comment are too great to go this route.

Copied for convenience:

- it limits the event names consumers can use (e.g. if we go for on-scroll:passive a consumer can never use a custom event called <whatever>:passive)
- only works for boolean flags, so will this work forever?
- complicates parsing of event listener attributes

**Comment by purtuga** [comment]
I too would love to see these quick/simple and intuitive shortcuts added to the Event Part.  Yes, you are correct in that there are limitations, but I don't think this proposed approach should cover all usage cases, but the most commonly used ones.  `once` and `capture` would be great additions. Also, having some keyboard interaction helpers would also save allot of boilerplate code to filter out needed events. Example:
```
@keyup.enter
@keyup.esc
@keyup.tab
```
Even if this type of request does not fit in the core lit-html library, it would still be great if the EventPart could allows us to define custom "modifiers" so that we could define them ourselves. 

(ps. This is one the things I love best about VueJS - these small intuitive shortcuts that just feel natural when coding :) )

**Comment by b-strauss** [comment]
> I think the cons listed in that comment are too great to go this route.
> 
> Copied for convenience:
> 
> * it limits the event names consumers can use (e.g. if we go for on-scroll:passive a consumer can never use a custom event called :passive)



> * only works for boolean flags, so will this work forever?

I think this should _only_ work for boolean flags. For everything else the Object configuration should be used. IMHO currently it's a bit overhead for something as simple as a boolean `capture` flag.

```js
// js
element.addEventListener('scroll', this.onScroll);
element.addEventListener('scroll', this.onScroll, true);

// lit-html
html`<button @click=${clickHandler}>Click Me!</button>`

const clickHandler = {
  handleEvent(e) { 
    console.log('clicked!');
  }
  capture: true;
}
html`<button @click=${clickHandler}>Click Me!</button>`
```



> * complicates parsing of event listener attributes

I have no knowledge about the cost of parsing this, but wouldn't `attribute.split('.')` be enough?

**Comment by purtuga** [comment]
:)
Or (using array):
```javascript
html`<button @click=${ [ this, { ...eventListenerOptions } ] }>Click Me!</button>`
```

**Comment by justinfagnani** [comment]
@kenchris's example is what's implemented now. And if the listener is a function it can have options directly in the function. This works great with class methods.

**Comment by justinfagnani** [comment]
Since @kenchris's alternative is what's already implemented, and I'm very wary of adding additional parsing code to template prep, I'm going to close this.

@purtuga's example of other modifiers is interesting and a slightly different proposal from this. I'm intrigued by it, but also still don't want to complicate parsing. A new issue to discuss that would be welcome.
