### ISSUE TITLE
Recent change to guard is broken if guard is an empty array

### ISSUE THREAD

**Issue by akc42** [Polymer/lit-html#682]
I am using guard to guard with an empty array.  If I replace that array with another empty array, guard does not notice the change and therefore does not re-evaluate what it is guarding.

This is a change in behaviour from before the ability to guard multiple values.  Changing on empty array for another then would re-evaluate what was being guarded.

**Comment by ruphin** [comment]
This is because `guard` now accepts an array with multiple objects instead of comparing the first argument object directly.

The easy fix when you want to guard on array-like object identity, you can do so by wrapping it with another array, like so:

 ```js
let arrayObject = [];

html`
  <div>
    ${guard([arrayObject], () => html`...`)}
  </div>
`
```

-------

Note that this is a very unusual use case, because you usually care about the identity of the contents of an array, but not the identity of the array object itself. If you pass your template an empty array it should render the same regardless of the identity of the array object.

To check if you need to update (which is what `guard` is for) you mostly want `[1,2,3] === [1,2,3]` and `[1,2,3] !== [1,2,4]`. The new implementation does exactly this when you pass it the array objects directly. The old implementation would consider all these unequal because the array objects are different even when the contents are the same.

If you want to update when an object identity changes, use objects instead of empty arrays:

 ```js
let dataObject= { list: [...]};

html`
  <div>
    ${guard(dataObject, () => html`...${dataObject.list}...`)}
  </div>
`
```

That way your guard will pass through if the `dataObject` changes, even when the contained list stays empty.

**Comment by akc42** [comment]
I know there are workarounds the work - that's what I ended up using using.  In fact I had always wanted to have the array I was using (which was quite frequently, but not always empty) and another array which if changed should pierce the guard.  

However, I reported that as a breaking change because it broke my working code and it didn't need to be that way. `guard` could check if it is guarding an empty array and if it is it it could treat it the same was as it did before  - only using the array content comparison if it was a none empty one. 

As I happens  I regularly use empty objects as guard expressions too.  I actually did that because the earlier versions of guard didn't support multiple guard and I had such a case.  What I ended up doing in the "data model" part of my element was to change the identity of an empty object with a new one when either of my real triggering expressions changed.  Its too much hassle to go back and change it all now

**Comment by ruphin** [comment]
> Its too much hassle to go back and change it all now

Such are the woes of using pre-release software :)

On the idea of implementing `guard` to use object identity for empty arrays, I will argue that it currently works as expected. The assumption is that when the argument is an array, we are reasoning about a list of items, and thus we should be using list equality, and not object equality, regarless of the content of the array. Two empty lists are the same, so `[] === []` is the expected outcome. Until we reach at least the 1.0 release, we should not be let backwards compatibility influence design decisions.

**Comment by mariusGundersen** [comment]
Guard could be variadic instead of taking an array, then it would have been backwards compatible and it will handle multiple objects.

**Comment by kevinpschaaf** [comment]
This was indeed a breaking change [and documented as such](https://github.com/Polymer/lit-html/blob/master/CHANGELOG.md#changed).

The change was made because the original guard had a flaw in that if your template function depends on more than one property, you could end up rendering stale data.  Consider:

```html
<ul>
${guard(list, () => list.filter(item => item.value < max).map(item => html`
   <li>${item.value}</li>
`))}
</ul>
```

In the above example, the list would re-render if `list` changed, but not if `max` changed. Thus the need for variable number of dependencies to dirty-check.

We considered varargs, but API design-wise, we like enforcing that varargs come last, and we _also_ like the template function coming last (dependencies before template) -- so we had to choose, and we landed on "array of dependencies" as first argument.  However, since it may often be called with one argument, made putting a single argument in the array optional.  

So it's less that arrays are treated differently than objects, more that the first argument _should be an array of dependencies_ (which may also be arrays), but the API has a shorthand allowing you to elide the array for only one dependency.

However, if the single dependency is an array, it should still be put in an array to disambiguate it as a dependency and not the list of dependencies. I'm going to go ahead and close this issue as WAI.
