### ISSUE TITLE
Custom element upgrading

### ISSUE THREAD

**Issue by lastmjs** [Polymer/lit-html#701]
What happens when custom elements get upgraded after the template they are in has already been rendered with some props? I believe I'm experiencing behavior where the properties on an upgraded custom element are not getting set after the upgrade. I'm working on a small reproducible example that I can share, but the basic gist is that I have a custom element that has not been upgraded as part of the initial template render, and I use a dynamic import to load the module that contains the custom element definition. After the element is upgraded, the properties that were supposed to be bound do not call the setter. I have a setter on the custom element that is never set by lit-html.

**Comment by lastmjs** [comment]
Here's the example. If you uncomment the import at the top it works, but if you dynamically load the `test-set-prop` element you'll see that the `prop` setter is never called: https://codesandbox.io/s/yo4xrmr7z

**Comment by justinfagnani** [comment]
Lit-html doesn't do anything special with properties, just sets them.

The problem you're seeing is happening because the setter is on the prototype and shadowed by the instance property. When you set the property again, just the instance property is updated, the setter isn't used. I think you'll find that the property is updated, you just don't see the setter being triggered.

The solution is to read off instance properties in the constructor, delete them, then re-assign them so that they'll go through the setters. This is what PolymerElement and LitElement do.

**Comment by lastmjs** [comment]
Whoa!!! It works thank you. Just to get this straight, this is happening because the property is getting set on the element before it is upgraded, thus only the prototype's properties are being set? And then when the upgrade occurs, no setters for me. I don't know how long that would have taken me to figure out on my own, so thank you very much.
