### ISSUE TITLE
[docs] Improve TOC handling

### ISSUE THREAD

**Issue by arthurevans** [Polymer/lit-html#714]
This is a general wishlist item for all the new sites, for post 1.0.

It would be nice to have better handling of the TOC. Either a floating TOC on the right like we had on the old Polymer site, or integrated into the left navigation.

Even swankier would be one of those TOCs that highlights the current heading as you scroll.

**Comment by arthurevans** [comment]
cc: @katejeffreys @yuinchien @keanulee

**Comment by justinfagnani** [comment]
I'm a big fan of the TOC being integrated into a single left-hand nav like the Vue docs here: https://v1.vuejs.org/guide/

**Comment by yuinchien** [comment]
Agree with @justinfagnani that a single left-hand nav is nice, if we can keep the hierarchy to 2-tier, 3 tier navigation gets too complex.

**Comment by katejeffreys** [comment]
Single left nav that expands to at most one level of sub-toc would be great. Agree with Yuin that 3 tiers of nav is too much. 

I do think we need to do something with the page TOCs as soon as possible because they're quite intrusive. Floating TOC for wide enough screens would be great. For narrower screens, idk

If we keep the mapping of toc item --> page and sub-toc item --> h2 page header, the pages could get very long. I would like to have "back to top" links and have each heading be a link so that people can right-click and get the URL complete with anchor from them.
