### ISSUE TITLE
problem binding to input "checked" property

### ISSUE THREAD

**Issue by akc42** [Polymer/lit-html#732]
I'm trying to create a set of tabs that work with hidden `<input type="radio">` inputs.  I am trying to do this via  html`<input id="state" type="radio" name="${this.group}" ?checked="${this.checked}"/>`

Whilst I can _set_ the checked property I cannot reset it, setting `this.checked` to false removes the `checked` attribute, but does not reset the underlying input property. 

The only way I have found to work around this is (in addition to above) use `this.shadowRoot.querySelector('#state')` to locate the element and then directly change it in `updated(changed)` thus
```
  firstUpdated() {
    this.inputEl = this.shadowRoot.querySelector('#state');
  }
  updated(changed) {
    if(changed.has('checked')) {
      this.inputEl.checked = this.checked;
    }
    super.updated(changed);
  }
``` 
Is there (or perhaps should there be) a way to set html properties rather than attributes in lit-html?

**Comment by LarsDenBakker** [comment]
If you want to set a property, use this:

`<input id="state" type="radio" name="${this.group}" .checked=${this.checked} />`

**Comment by akc42** [comment]
Yes that works. It is worth noting that  you have to use the CSS Pseudo Selector `:checked` to pick up the input state and put an accent on the tab that is currently selected if you set the property rather than the attribute.

It might be useful  if the documentation mentioned how to do this, because I don't think I would have figured it out on my own

**Comment by LarsDenBakker** [comment]
I think with native inputs, the attribute sets the initial value and from there on the property manages the current state. It's not directly related to lit-html, you would encounter this whenever you use native inputs right? 

The CSS is because `[checked]` acts on an attribute so it won't match when you set the property.

**Comment by justinfagnani** [comment]
We can see if this fits in the docs somewhere, but it's not really a lit-html issue as much as a HTML/DOM issue. If you want to update `value` and `checked` on an input, you have to set a property.

Closing for now, but maybe @arthurevans can see a place to mention this. Maybe in the property binding section as a use case?

**Comment by arthurevans** [comment]
We did have some doc in Polymer on special cases people might need to be aware of when binding to DOM attributes/properties. So we could probably do that, yes.

**Comment by nboisteault** [comment]
I tried to force checked property to false this way :
`<input id="state" type="radio" name=${this.group} .checked=${false} />`
This part in render when checkbox is checked so I expect to never see this checkbox checked, but in fact the behavior remains the same.

**Comment by LarsDenBakker** [comment]
For boolean attributes you need to use `<input id="state" type="radio" name=${this.group} ?checked=${false} />`

**Comment by nboisteault** [comment]
I want to force the checked property not the attribute one which is only useful when page loads.

**Comment by Westbrook** [comment]
@nboisteault you can't manage a property with a static value `.checked=${false}`. Because the value for `false` when the template is interpreted will never change, `lit-html` will never see it as having become dirty and it will only set the property on the `input` the first time. If you want to ensure that it is always the same value you have to do that in the property lifecycle, a la:
```
static get properties() {
   return {
       radioChecked: { type: Boolean}
   }
}
render() {
    return html`
        <input id="state" type="radio" .checked=${this.radioChecked} @change=${e => this.radioChecked = true;} />
        <input id="state" type="radio" @change=${e => this.radioChecked = false;} />
    `;
}
updated(changes) {
    if (changes.has('radioChecked')) {
        this.radioChecked = false;
    }
}
```
This way the binding accepts the user input but overrides it with the "correct" value. I'm a little out of practice of binding to a radio group, so there's probably a much cleaner way to do that, but you have to keep the class property in sync with the value of the DOM property and then use the lifecycle methods to validate that value.

Separately, if you really don't want the value to change, you can use `[disabled]` on the `input` or `pointer-events: none` in its CSS, but that depends on the specifics of the goals you have for your element.
