### ISSUE TITLE
Feature Request: Append pre-existing node children back into shadowDOM upon NodePart creation

### ISSUE THREAD

**Issue by pgoforth** [Polymer/lit-html#736]
[Currently, on initial NodePart creation, rendering a template into a container will remove all pre-existing children from the container, then will render the template into the shadow DOM.](https://github.com/Polymer/lit-html/blob/c1b3bfd0d4fb5d2db2a897c487a28f6737168734/src/lib/render.ts#L47-L54)
However, the rendered template could potentially contain slots which are intended to contain the pre-existing children. Appending the children back into the container would allocate them into the appropriate slots in the shadow DOM.

**Comment by justinfagnani** [comment]
Slots aren't intended to contain existing children, but children of the host element the ShadowRoot is attached to. Direct children of slots are only default content for the slot. That should generally be part of the template.

**Comment by pgoforth** [comment]
@justinfagnani 
Then what is the intention behind removing the children from the container? If you do not remove them to begin with, they will never display because the shadowRoot will display instead. If you add them back into the container, they *might* display if you have a slot in your template. If there is no slot, the children would not display anyway. Shouldn't that be the decision of the developer rather than the framework?

**Comment by ruphin** [comment]
The container is the element that is directly rendered to. When you render into a ShadowRoot, lit-html removes elements from that ShadowRoot before rendering into it, and it does not affect the LightDOM of the parent Element.

You can see that lit-html does not remove elements in the LightDOM when rendering into a ShadowRoot: https://codepen.io/ruphin/pen/qLyQvB?editors=1010

I think the confusion here stems from the fact that the `render` function renders into a `container` and not the ShadowRoot of the `container`. If you want to render into a ShadowRoot, you must pass the ShadowRoot as the `container` argument, and `render` will clear the content of the ShadowRoot before rendering into it, and not the content of the host Element.

**Comment by pgoforth** [comment]
@ruphin I see your point. Perhaps this is more of request for `lit-element` and it's implementation of `lit-html`. I'll see if I can figure out a good implementation in that repo. Thanks for your help.

**Comment by ruphin** [comment]
As far as I know `lit-element` also does not change an element's LightDOM unless explicitly instructed to do so. Can you give an example where the behaviour you describe happens?

**Comment by pgoforth** [comment]
The issue is that `lit-html` completely overwrites the DOM of the element you are targeting. If you were trying to preserve existing children, you would have to remove them, then re-append them. You could not currently do what you could in React using a template:
```JS
html`<div>Added Element</div>${this.children}`;
```
That's more along the lines of what I'm trying to accomplish.

**Comment by ruphin** [comment]
> The issue is that lit-html completely overwrites the DOM of the element you are targeting.

This is the intended behaviour. lit-html is used to control rendering in a certain context. When you use lit-html to render into a context, it cannot co-exist with other rendering methods in that context, which includes having DOM nodes in that context (regardless if they are pre-existing or added later).

React can do what you describe because it has a different implementation; it checks the current content of the DOM vs the requested template and makes the required changes. Lit-html does not have to do these things, but in order to skip these steps lit-html must have full control over the content of the target context. If you want a rendering engine that can do differential rendering, you should use React (or some derivative VirtualDOM engine).

If you must render content in a contaner that already has other content, you can easily do that with lit-html by creating a new container as a child of that context and let lit-html render into that.

```js
document.body.innerHTML = "<div id='some-container'><span>Existing content</span></div>"

const existingContext = document.getElementById('some-container');
const litContainer  = document.createElement('span');
existingContext.insertBefore(litContainer, existingContext.firstChild);

const myTemplate = html`<div>Added Element</div>`;
render(myTemplate, litContainer);
```

Note that this issue don't exist if you use declarative rendering systems (like lit-html) all the way down, instead of using lit-html to patch existing DOM structures.

**Comment by justinfagnani** [comment]
I could see a reasonable feature request that `render()` should no clear the container, so that rendering and updating will happen at the end of the container. We could add an option for this. It seems to be very different from the OP's questions about slots though.

**Comment by pgoforth** [comment]
@ruphin 
The idea is that you would not need an additional container to accommodate things like CSS siblings and flex-box

@justinfagnani 
The reason I referred to slots was due to the fact that slots allow for segmentation of existing children through a template without having to implement a way of tracking them. What I would really love to be able to do would be to create a custom element that would leverage `lit-html` to append or prepend, arbitrary DOM nodes around the children passed to an element. For example, my backend generates markup that looks like this:
```HTML
<my-custom-list>
  <custom-list-item>Item 1</custom-list-item>
  <custom-list-item>Item 2</custom-list-item>
  <custom-list-item>Item 3</custom-list-item>
</my-custom-list>
```
Be able to define the render of `<my-custom-list>` like this:
```JS
class MyCustomList extends HTMLElement {
  get template() {
    return html`
      <my-custom-header></my-custom-header>
      <ol>${this.children}</ol>
      <my-custom-footer></my-custom-footer>
    `;
  }

  connectedCallback() {
    this.render();
  }

  // Arbitrary render callback
  render() {
    render(this.template, this);
  }
}
```
Once it renders on client side, it would look like this (content is arbitrary):
```HTML
<div class="customList">
  <div class="customListHeader">Description of List</div>
  <ol>
    <li class="customListItem">Item 1</li>
    <li class="customListItem">Item 2</li>
    <li class="customListItem">Item 3</li>
  </ol>
  <div class="customListFooter">More Options</div>
</div>
```
Subsequent calls to render would not work because `this.children` would contain all the new DOM nodes. I implemented a partial solution using `lit-element`, but it required re-adding the DOM nodes that were removed by `lit-html` as you can see [here](https://github.com/Polymer/lit-element/issues/42#issuecomment-442894676).

I would love to be able to avoid Shadow DOM altogether because (currently) Shadow DOM does not support CSS inheritance from the Light DOM. Rendering into slots, however, allows you to keep a defined structure and renders the slot content into the Light DOM where your CSS can cascade normally.

**Comment by justinfagnani** [comment]
@pgoforth I suspect you're misunderstanding ShadowDOM and `<slot>` a bit.

> slots allow for segmentation of existing children through a template without having to implement a way of tracking them.

This isn't what slots do. They don't have anything to do with templates: they only allow projecting light-dom children into shadow-dom.

And your code isn't using `<slot>` where it should:

Instead of this:
```js
    return html`
      <my-custom-header></my-custom-header>
      <ol>${this.children}</ol>
      <my-custom-footer></my-custom-footer>
    `;
```

Do this:

```js
    return html`
      <my-custom-header></my-custom-header>
      <ol><slot></slot></ol>
      <my-custom-footer></my-custom-footer>
    `;
```

And slots will just work.

Trying to determine where existing content should be moved and interpolated into templates is too complicated and a job for Shadow DOM, not lit-html. Shadow DOm was built for this, I'd reccomend using it.

**Comment by ruphin** [comment]
The problem with the approach you suggest is that the children of a Custom Element are not guaranteed to exist during the `connectedCallback`. In your example above the `<my-custom-list>` element may not see the `<custom-list-item>Item 1</custom-list-item>` elements until they are inserted into the DOM, which may happen after the `connectedCallback` on CustomList is called. That means that when you call `render`, `this.children` may be empty. Even if we rewrote some parts of lit-html, you still would not be able to do what you suggest.

One of the reasons we use ShadowDOM with the `slot` approach is exactly to solve this problem, because it works around this timing issue.

You can see here an example of how timing affects the interaction with LightDOM and Custom Elements:
https://codepen.io/ruphin/pen/omjYQj?editors=1001

Effectively what you're trying to do is manipulate existing DOM structures, which is not something lit-html is designed to do. You can still use it to render new content, but you have to do the DOM manipulation part (which parts to insert where) yourself.

**Comment by pgoforth** [comment]
@justinfagnani 
I'm not misunderstanding Shadow DOM, I'm trying to exploit it in a way it was not designed for.

In your example, `<my-custom-header>` would be rendered into the ShadowDOM, where it's isolated from all CSS cascading...not what I want.

**Comment by innerop** [comment]
@justinfagnani 

> I could see a reasonable feature request that `render()` should not clear the container, so that rendering and updating will happen at the end of the container. We could add an option for this. 

Please do. But we should be able to choose wether rendering happens at beginning or end of the container, or remove any existing nodes. Right now, when I render into a container that has a nested container that I had rendered into the nested container's children are removed.

**Comment by jonnyarnold** [comment]
I stumbled across this with a similar request: we have a set of nested web components that we'd like to render elements around:

```html
<!-- Initial HTML -->
<my-chunk>
  <my-chunk>First paragraph.</my-chunk>
  <my-chunk>Last paragraph.</my-chunk>
</my-chunk>

<!-- Desired Final HTML -->
<my-chunk>
  <my-intro>Chunk 1</my-intro>
  <my-chunk>
    <my-intro>Chunk 1.1</my-intro>
    First paragraph.
    <my-outro>End of Chunk 1.1</my-outro>
  </my-chunk>
  <my-chunk>
    <my-intro>Chunk 1.2</my-intro>
    Last paragraph.
    <my-outro>End of Chunk 1.2</my-outro>
  </my-chunk>
  <my-outro>End of Chunk 1</my-outro>
</my-chunk>
```

To make things more interesting, we're *not* using the Shadow DOM as we have an existing, separate stylesheet file.

The solution we found was pretty straightforward: get references to the initial children on first render, and inject them wherever you like in your template:

```ts
import { customElement, html } from "lit"

@customElement
class MyChunk extends LitElement {

  createRenderRoot() { return this }

  private initialChildren?: Element[]
  render() {
    if (this.initialChildren === undefined) {
      this.initialChildren = Array.from(this.children)
    }

    return html`
      <my-intro>...</my-intro>
      ${this.initialChildren}
      <my-outro>...</my-outro>
    `
  }

}
```

The benefit of this approach is that you can put the initial children *wherever you like* in your template, not just at the start or end.

I appreciate most people use the Shadow DOM, but I thought I'd drop this here in case it helped someone else. Also, if you spot an issue with this strategy, do let me know!
