### ISSUE TITLE
::part has been supported in Chrome 73 and ::theme soon (hopefully)

### ISSUE THREAD

**Issue by motss** [Polymer/lit-html#751]
I guess this is also part of the effort for `webcomponentsjs`'s ShadyCSS to support that. What's the plan from the lit team for this feature?

**Comment by stramel** [comment]
I know that there are a couple solutions both with downsides. Turns out it is hard to polyfill performantly.

Polymer team has an experimental one. https://github.com/PolymerLabs/part-theme/blob/master/README.md

Vaadin has a mixin that they use for their components. https://github.com/vaadin/vaadin-themable-mixin

**Comment by justinfagnani** [comment]
Like Constructible StyleSheets, there's nothing really to do in lit-html for this, but there may be in LitElement.
