### ISSUE TITLE
Dynamic end tag produces unexpected output

### ISSUE THREAD

**Issue by rictic** [Polymer/lit-html#758]
What is the expected behavior of this code:

```typescript
html`<div>hello world</${'div'}>`
```

Currently it produces something like:

```html
<!----><div>hello world<!--<!--{{lit-39093325954025593}}---->&gt;</div><!---->
```

Which, stripping the comments, is:

```html
<div>hello world&gt;</div>
```

It's pretty far into edge case territory, and we might not care about this case, but we do handle someone attempting to write a dynamic opening tag more gracefully.

```typescript
html`<${'img'} src="foo.jpg">`
```

Becomes:

```html
&lt;img src="foo.jpg"&gt;
```

**Comment by ruphin** [comment]
> What is the expected behavior of this code

The expected behaviour is undefined. Lit-html does not support dynamically defined html tags, in both opening or closing tags. The fact that the dynamic opening tag leads to a more "useful" result is mostly coincidental.

There are many ways to construct html templates that lead to strange results, like double attribute definitions or other weird corner cases that aren't supported or valid.

I think the correct path is to clearly indicate in documentation that dynamic tags are not supported in any way shape or form.

**Comment by rictic** [comment]
I agree that this is not code that we want people to write. 

For context, I'm writing some tests of the security properties of lit-html. With https://github.com/Polymer/lit-html/pull/750 set up, it's fairly hard to accidentally write unsafe code with lit-html, which is a very nice property to have. Not everyone will read all of the documentation, and even for those that do, it's easy to forget sometimes.

The fact that ```html`<${'div'}>`;``` does not produce a `<div>` is very nice from a security perspective. The behavior of the closing tag is much less of an issue, I haven't been able to construct an exploit from it, but I wanted to get some thoughts on what guarantees we want to make about the code.

**Comment by justinfagnani** [comment]
```js
html`<div>hello world</${'div'}>`
```

producing

```html
<!----><div>hello world<!--<!--{{lit-39093325954025593}}---->&gt;</div><!---->
```

is problematic only if it break templates. If we detect the marker in the comment text so that we can align the parts and values array correctly, then this output is fine. The expression won't have the intended effect, but it won't misalign values into the wrong parts, or worse, throw an expression.

This is definitely worth a test case.

**Comment by justinfagnani** [comment]
Added a test to confirm that there's no crash or binding-skew.
