### ISSUE TITLE
part value types

### ISSUE THREAD

**Issue by yorrd** [Polymer/lit-html#803]
When I write 

`<button @click=${e => console.log(e.detail.value)} />`

obviously, TypeScript doesn't know about the type of the callback. I'm not sure whether here or on the TypeScript issue tracker is a good place to discuss this, but can we somehow make this happen? If someone has a good pointer for me how to achieve this, I'll gladly make a proof of concept repo.

**Comment by Lodin** [comment]
`lit-html` template is basically a string, so it is impossible to get any types from it until Typescript adds support for `lit-html`. However, due to the string nature of HTML and all tricks hidden under the hood of the web components, I hardly believe they're going to do it eventually. 

You can try in Typescript issue tracker though. Please provide a link to your issue, I would like to follow it as well.

**Comment by Lodin** [comment]
Personally, I'm going to use simple typing like following:
```
<button @click=${(e: CustomEvent<EventDetailType>) => console.log(e.detail.value)} />
```

**Comment by yorrd** [comment]
shouldn't it be possible to infer Type just by knowing that it's an event handler though? Can TypeScript plugins interpret surrounding strings?

**Comment by justinfagnani** [comment]
See this discussion in the TypeScript repo: https://github.com/Microsoft/TypeScript/issues/29432

We have designs to allow type checking, but it's going to require collaboration between the teams.

Going to close this as we need tsc feature first, but I'll open a design issue for type-checking soon.
