### ISSUE TITLE
Move LitElement's css template tag into lit-html

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/lit-html#823]
Contextual sanitization currently has a hole around nested templates inside `<style>` tags:

```js
html`
  <style>
    ${html`
      body {
        color: ${userValue}
      }
    `}
  </style>
`;
```

Here the binding for `${userValue}` might not be rejected by a sanitizer because it doesn't have a known parent element.

We can lock this situation down by adopting `css` and `CSSResult` from LitElement and implementing a sanitizer that only allows `CSSResult`s in text bindings in `<style>` elements:

```js
html`
  <style>
    ${css`
      body {
        color: ${userValue}
      }
    `}
  </style>
`;
```

This would be rejected if `userValue` is not also a `CSSResult`.

cc @mikesamuel @sorvell @rictic

**Comment by rictic** [comment]
Importantly, CSSResults are only constructible with the `css` template tag, which does not allow interpolation of any kind (only allows strings from source code), and the `unsafeCss` template tag, which does allow interpolation, but which can be forbidden, linted against, or carefully reviewed.

Inside google we're currently patching LitElement to not expose `unsafeCss` at all.

**Comment by daKmoR** [comment]
If css would allow for true javascript numbers as possibly outlined like here https://github.com/Polymer/lit-element/issues/488#issuecomment-460603401 then `unsafeCSS` would probably not have many real use cases anymore (maybe some rare edge cases).

I hope this issue can be addressed before moving it over 🤗

**Comment by arthurevans** [comment]
This impacts both sets of docs, so if/when this change goes through, please open docs issues for lit-html & lit-element to update the existing docs.

**Comment by SampsonCrowley** [comment]
@daKmoR how would you handle importing an image and using it in a ` css`` ` tag without `unsafeCSS`? right now it's currently impossible to just interpolate a simple string, and i really don't understand why that is something that is even a restriction. what's the point of not allowing the developer to interpolate variables as needed? what in CSS is so dangerous that it needs to be cleaned?

**Comment by rictic** [comment]
A constant string authored by the developer of a site is safe. A string controlled by a malicious source is not safe. The library can't know the difference between a string that's a build-time constant vs a string that comes in from an untrusted source.

Here's one article that discusses what an attacker can do if they can inject CSS into your site: https://medium.com/bugbountywriteup/exfiltration-via-css-injection-4e999f63097d

**Comment by rictic** [comment]
For the case where you're importing the URL image yourself, the developer can verify by hand that `unsafeCss` is safe. 

Alternatively, since that's a nonstandard build-time transform, it might be possible to transform the code that generates the bg-skyline.jpg module into one that exports a lit css literal. Or to do constant folding into the css literal in HomePage.

**Comment by hyperpress** [comment]
Part of the reason that unsafeCSS is used is because Google is ultra-strict
about security on code they use. While you or a developer might think it's
okay to self-audit to make sure what you are using is secure, the fact
remains is that there are a lot of unknowns out there. And I can think of a
half dozen reasons off the top of my head of how the library could be
abused with the project owner wanting to make sure that reasonable bases
are covered. I hope that makes sense.

<https://themesurgeons.com>

<https://themesurgeons.com>

**Comment by SampsonCrowley** [comment]
@rictic @hyperpress which is why i asked @daKmoR how he would expect to do imports if `unsafeCSS` was removed

> then `unsafeCSS` would probably not have many real use

importing images to use as a background seems like a perfectly common use case to me

**Comment by kwaclaw** [comment]
Just a comment: I find the css template tag useful outside of lit-element.

**Comment by justinfagnani** [comment]
We've moved `css` into `@lit/reactive-element`. I'm unsure about adding it to lit-html at this point. It's pretty separate and typed to potentially return a CSSStyleSheet, which wouldn't integrate into lit-html bindings nicely.
