### ISSUE TITLE
LitApp bad performance with repeated elements + css animation

### ISSUE THREAD

**Issue by anargu** [Polymer/lit-html#836]
# Description
I was working with Lit-html and Lit-Element in a WebApp. Then I noticed there is a lag when I create **n** div elements like cards (with simple info) and css animations in loop. The lag is noticed at scrolling the page. Then I replicate the same structure with React App and the behavior is different, the scrolling is smooth, there is not lag.

# Steps to Reproduce

You can see this comparison or benchmark by running a simple webapp created in lit-app and react-app from the repo I did: [see repo](https://github.com/anargu/Little-Benchmark-LitApp-ReactApp)

## Expected Results

No lag with lit-html or lit-element. At least, scrolling behavior should run smooth like React

## Actual Results

scrolling behavior is laggy

Note:
I was searching for related issues to this but I have not found any. If this issue should go to Lit-Element issues please tell me and I'll move it.

**Comment by Westbrook** [comment]
This is mainly due to your choice of drop shadow application `filter: drop-shadow(0px 4px 8px rgba(0, 0, 0, 0.15));` and the way that it isn't currently being applied to the React application. Check out the following Stackblitzes made from your repo where the shadow is applied in both cases causing an equal amount of jank:

LitElement: https://stackblitz.com/edit/8pkam5?file=box-card.js
React: https://stackblitz.com/edit/react-8r6lqv?file=BoxCard.js

In your repo's version of the React app the shadow is never applied due to the use of `:host {}` which has no effect on React components: https://github.com/anargu/Little-Benchmark-LitApp-ReactApp/blob/master/react-app/src/BoxCard.css#L1

When it is switched ON via:
```
.box-card-wrapper {
  display: block;
  text-align: center;
  filter: drop-shadow(0px 4px 8px rgba(0,0,0,0.15));
  color: grayLight1;
}
```
and
```
  render() {
    return (
      <div class="box-card-wrapper">
        <div id="box-card">
          <a href="#" class="chevron-right animate layer-1"></a>
          <a href="#" class="chevron-right animate layer-2"></a>
          <a href="#" class="chevron-right animate layer-3"></a>

          <div class="content">
            <span class="content-item">ITEM</span>
          </div>
        </div>
      </div>
    );
  }
```
The standard jank of such a highly difficult to paint style is evident in both places, much as would be expected to be evident in raw HTML/CSS.

The following LitElement based Stackblitz has the shadow turned off and exhibits the same speed you were experiencing in React under the same circumstances:
https://stackblitz.com/edit/8pkam5-bnpreh?file=box-card.js

**Comment by anargu** [comment]
I didn't notice that feature, sorry for the bad incorrect argument. I should read more about css filters and performance effects it implies. It's not related to lit-html or Shadow DOM. I'll update the repo. Thank you for your help @Westbrook
