### ISSUE TITLE
Include a small example for a Polymer 3.0 element in the README.md

### ISSUE THREAD

**Issue by MatxBerg** [Polymer/lit-html#88]
Hi,

I see the example with a 'generic' element using the 'render()' function. I was wondering if it was possible to add a simple example with a polymer 3.0 element to the readme file? Or at least define what the CoolLitMixin contains?

Thanks

**Comment by DiiLord** [comment]
I just wrote [lit-element](https://github.com/DiiLord/lit-element.git) which is a class that allows you to use lit-html easily with Custom Elements, especially if you are familiar with Polymer.

It is in really early stage, as I did it just this morning, but it seems to work as expected.

**Comment by kenchris** [comment]
I have something similar here: https://sensor-compass.appspot.com/scripts/lit-element.js

**Comment by nicolasparada** [comment]
![Impressive Very Nice](https://media.giphy.com/media/FxLtbu7KrGoKs/giphy.gif)

**Comment by KeithHenry** [comment]
I think a mixin is a better fit here, rather than extend a base class.

This way the mixin can be used with `Polymer.Element` or `Element` or anything else.

Something like...
```typescript
import { html, render as litRender } from '/modules/lit-html/lib/lit-extended.js';
export function WithLit<T extends Constructor<Element>>(Base: T) {
    return class extends Base {
        render(template: TemplateResult): void {
            ...
            const r = this.shadowRoot || this.attachShadow({ mode: 'open' });
            litRender(template, r);
        }
    }
}

export class MyElement extends WithLit(Polymer.Element) {
    ready() {
        super.ready();

        this.render(html`<div>${123}</div>`);
    }
}
```

`CoolLitMixin` is the other way round - expecting the extended base to have a `render` method and adding the result of that to the shadow DOM.

**Comment by justinfagnani** [comment]
@kenchris I have a little bit of feedback on your base class. Let me know if you want to chat about it :)

**Comment by kenchris** [comment]
@justinfagnani sure, I am interested. Tried to ping you in private on Twitter, but I think you don't follow me. What would be the best way to talk?

**Comment by kenchris** [comment]
I know it misses case conversion etc :) but that should be easy to add

**Comment by justinfagnani** [comment]
Honestly, I'd skip the case conversion and have the property definition include the attribute name. No ambiguity that way.

**Comment by daKmoR** [comment]
awesome idea :) just included the case conversation in my lit-element... but that sounds way nicer :)

**Comment by kenchris** [comment]
@justinfagnani I fixed your comments and pushed to a new repo: https://github.com/kenchris/lit-element

To anyone here: Tests and PRs are welcome :-)

**Comment by klebba** [comment]
@kenchris Can you add some commentary about why you use `Promise.resolve()` ahead of the render?

**Comment by kenchris** [comment]
@klebba read this: https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

Promise.resolve() basically puts it back on the event loop (makes it async), which is handy because it (invalidate) might be called from anywhere (ie from events themselves, timers etc) - that also makes things consistent.

Basically it becomes a microtask

 "Microtasks are usually scheduled for things that **should happen straight after the currently executing script, such as reacting to a batch of actions**, or to **make something async** without taking the penalty of a whole new task."

"The microtask queue is processed after callbacks **as long as no other JavaScript is mid-execution**, and at the end of each task. Any additional microtasks queued during microtasks are added to the end of the queue and also processed. Microtasks include mutation observer callbacks, and as in the above example, promise callbacks."

**Comment by web-padawan** [comment]
BTW, Polymer uses its own microtask implementation, see [here](https://github.com/Polymer/polymer/blob/master/lib/utils/async.html#L158):

> Note that microtask timing is achieved via a single `MutationObserver`, and thus callbacks enqueued with this API will all run in a single batch, and not interleaved with other microtasks such as promises. Promises are avoided as an implementation choice for the time being due to Safari bugs that cause Promises to lack microtask guarantees.

**Comment by kenchris** [comment]
I added a bit of documentation now: https://github.com/kenchris/lit-element/blob/master/README.md

**Comment by klebba** [comment]
@kenchris Thanks!

**Comment by kenchris** [comment]
@klebba I added some demos as well https://kenchris.github.io/lit-element/

I still need to make an npm module, but I have never done that before :-) so need to figure out how

**Comment by kenchris** [comment]
OK, so I published an npm module 'lit-html-element' for now, but I will want to fix paths etc

**Comment by NeoLegends** [comment]
Hey @kenchris! lit-element looks neat! I made a PR with some changes I think fit nicely.

---

We have an another stance on lit-html + web components: We created a combination of redux + web components + lit-html called [💪-html](https://github.com/Festify/fit-html). We tried to keep the total size of the library below 5kb to fit the original spirit of this library and we're introducing Redux into the mix for a cleaner application structure.

Would love to see some feedback. :)

**Comment by kenchris** [comment]
Hi there @NeoLegends - cool, I will have a look :-) I just got back from the US so I am a bit jetlagged still though.

I have the plan to ship my mini element into a set of mixins, but I have to find the proper way of doing so.

**Comment by justinfagnani** [comment]
FYI, there's a lit-element in progress here: https://github.com/PolymerLabs/lit-element

**Comment by justinfagnani** [comment]
Closing as more relevant to lit-element.
