### ISSUE TITLE
How is lit-html efficient without template compilation?

### ISSUE THREAD

**Issue by DominicTobias** [Polymer/lit-html#944]
Hi,

Not an issue so closing this, but would be grateful if you could shed some light!

Really enjoying this lib and it's simplicity and use of JS for logic.

Handlebars has `compile()`, JSX has build time compilation to functions. I'm wondering how, since we don't pre-compile lit templates, are they still efficient? Is there some clever magic to compile the html`''` templates only once or is it doing this work every execution? If so is it really so fast at compiling strings that this is irrelevant and it can be done every time execution??

> TemplateResult - a record of the template to render and data to render it with. TemplateResults are very cheap to produce and no real work actually happens until they are rendered to the DOM.

Thanks

**Comment by justinfagnani** [comment]
lit-html prepares templates the first time they're rendered, not every execution. The preparation step records where the expressions are in the DOM so that on the changing expressions are ever updated.

See this talk: https://www.youtube.com/watch?v=ruql541T7gc
We also have a wiki page, but it's pretty incomplete: https://github.com/Polymer/lit-html/wiki/How-it-Works

**Comment by DominicTobias** [comment]
Ah cool 😎 thanks

**Comment by MatanYadaev** [comment]
@justinfagnani Any plans to complete the wiki page?
