### ISSUE TITLE
Using other library messes with template

### ISSUE THREAD

**Issue by zksward** [Polymer/lit-html#959]
# Description
When using another libraries components the DOM is manipulated outside of lit-html's rendering and unreliable results occur. Specifically, I'm using Atlassian's web components and they add extra nodes to the DOM that I believe is messing with the node counts in lit-html's rendering process. Are there any known workarounds for this particular gotcha?

**Comment by justinfagnani** [comment]
Could you make an online repro, say on StackBlitz, so I could see what's happening?

In general you cannot modify the DOM under lit-html's control, because we rely on the structure of the DOM staying the same to make updates. In practice there's actually a fair bit of leeway, and as long as you leave let-html's marker nodes, and certain static nodes that parts are anchored to, alone, then updates will work fine.

Usually, only one library is trying to manage DOM in any given container, like a LitElement's shadow root. So I'm curious what the Atlassian components are doing to interfere with lit-html. Do you have a link to their components?

**Comment by zksward** [comment]
Sure, I'll try getting something together in StackBlitz and update when that's done.

**Comment by justinfagnani** [comment]
It's a pretty fundamental property of lit-html that it needs to own the DOM it renders. In some cases it can handle outside mutations, but it's always a bit dangerous. Since this is just the way the library works, I'm going to close the issue.
