### ISSUE TITLE
[feature request]directive in template

### ISSUE THREAD

**Issue by zzzgit** [Polymer/lit-html#985]
```js
const employeeList = (employees) => html`
  <ul>
    ${repeat(employees, (employee) => employee.id, (employee, index) => html`
      <li>${index}: ${employee.familyName}, ${employee.givenName}</li>
    `)}
  </ul>
`;
```

This snippet is from the official documentation. It's reasonable.
However, some other libs like `vue`, using a more declarative way:

```vue
<ul>
<li v-for="(employee, index) in employees" key="employee.id">${index}: ${employee.familyName}, ${employee.givenName}</li>
</ul>
```

The directives are just in template.

Now what I want to say is can we change `lit-html` in that way too?

```js
const employeeList = (employees) => html`
  <ul>
    ${  html`
      <li lit-for="(employee, index) in employees" lit-key="employee.id">${index}: ${employee.familyName}, ${employee.givenName}</li>
    ` }
  </ul>
`;
```

**Comment by justinfagnani** [comment]
We can't do this. We don't look for identifiers in templates, and don't want to because other static analysis tools like TypeScript, Closure Compilers, etc., won't know that variables are being referenced from strings. We also can't repeat a portion of a template string - every template string is turned into an HTML template directly, and we can only stamp out whole templates.
