### ISSUE TITLE
TypeError: Cannot read property 'nextSibling' of null 

### ISSUE THREAD

**Issue by nokisnojok** [Polymer/lit-html#987]
#### Live Demo

https://stackblitz.com/edit/lit-element-example-yqhp16?file=index.js

#### Steps to Reproduce
1. click button which innerHTML is 'click this to change data'. 

#### Expected Results
No error is throw

#### Actual Results
TypeError: Cannot read property 'nextSibling' of null

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

### Versions

- lit-element: v2.0.0-rc.2
- webcomponents: v2.2.3

**Comment by abraham** [comment]
You're [overriding `createRenderRoot`](https://lit-element.polymer-project.org/guide/templates#renderroot) which disables the [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) and then you are nesting elements within your custom element without using a [`<slot></slot>` in the template](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot).

If you remove the uses of `createRenderRoot` and add `<slot></slot>` to each template there isn't an error, all the elements are rendered, and the counter works.

https://stackblitz.com/edit/lit-element-example-nk2u9j?file=index.js

**Comment by ernsheong** [comment]
Possibly Related: https://github.com/Polymer/lit-html/issues/293

**Comment by sorvell** [comment]
The exception should be fixed in the next release of lit-html via https://github.com/Polymer/lit-html/issues/293.

As noted above, the use case here is a bit pathological since both the `<t-a>` element and the `<t-b>`element are rendering to the childNodes of `<t-b>` (since `<t-b>` overrides `createRenderRoot` and returns `this)`. What will probably happen after the next release of of lit-html fixes the exception is that the `<t-b>` template will render replacing the DOM created by `<t-a>`. This kind of composition is only supported using Shadow DOM and `<slot>`.
